### ISSUE TITLE
I can't move on the iPhone

### ISSUE THREAD

**Issue by Niklas420** [iam4x/pokemongo-webspoof#100]
Sorry for my bad English. I am using google translate .
when I run the app , I can indeed on the mac but move on my iPhone itself does nothing

**Comment by Raizelian** [comment]
That is what this app is supposed to do. It only allows movement using the Mac.
If you want to move on the iPhone, too, I would suggest using a tweak such as PokemonGoAnywhere (jailbroken phones) or Tutuapp (non-jailbroken).

**Comment by iam4x** [comment]
wontfix, it's not supported and won't be by this project.
