### ISSUE TITLE
Walking Speed to Hatch Eggs!

### ISSUE THREAD

**Issue by jctissier** [iam4x/pokemongo-webspoof#103]
Hi,

Thank you for the amazing app, has been really easy to use so far. I would recommend adding an extra feature to the speed of movement. At about 12km/h for your walking speed, the app doesn't recognize it as real walking so if trying to hatch an egg, it won't count the distance. However, at around 5-6km/h it does. 

If you add an extra speed in rc/models/autopilot.js of 6km/h, we could just hatch eggs all day long. Just a suggestion :)

**Comment by d3viant0ne** [comment]
In reality, the speed values should be configurable with sensible defaults

**Comment by lhecker** [comment]
The common believe seems to be that 10 km/h is the speed limit to consider the movement as "walking". So I'm currently using a walking speed of 9 km/h and it works perfectly.

**Comment by d3viant0ne** [comment]
@lhecker - I'm using the same setting. 9km/h seems to be the sweet spot for speed / hatching.

**Comment by iam4x** [comment]
Fixed with #130 will be in next release 👍
