### ISSUE TITLE
Missing pokemonLocation.gpx

### ISSUE THREAD

**Issue by Padrino02** [iam4x/pokemongo-webspoof#105]
Where is the file located at_ I downloaded the whole folder with the Xcode project inside but i can-t find the .gps file... Help pls

**Comment by CrazyJayson** [comment]
move arround with arrow key and it should appear

**Comment by Raizelian** [comment]
The file is inside the application, Xcode detects it automatically; anyway, the exact path is:

`/private/var/folders/z7/kf4ry2bd3t76lx8n8prrmhqc0000gn/T/tmp-19322zgtnwcZkGci/pokemonLocation.gpx`

If it doesn't show up for you under the Debug menu > Simulate location, simply drag the map around a bit and it should come up as an option.

**Comment by Padrino02** [comment]
Thanks a lot guys it works now :)
Hope the Servers get stable soon

**Comment by hhuesca** [comment]
Hey guys, i've checked on that location and i can't find the file. Can you help me please?

**Comment by Raizelian** [comment]
This is the set path, to which you can gain access by "Finder > Go > Go to Folder..." option:
`/private/var/folders/z7/kf4ry2bd3t76lx8n8prrmhqc0000gn/T/`

From the "T" folder on, the folders are temporary and thus they may change each time you open the Xcode project; to see which folder your .gpx file is in, simply do a search for "pokemonLocation.gpx" restricted to the "T" folder only, and you will find it. Once you click on it, you can see its full path, too.

**Comment by hhuesca** [comment]
Thank you my friend... I've found the folder at: /private/var/folders/zz/zyxvpxvq6csfxvn_n00000yw00007q/T/ but it's empty. Also I´ve made the search, but simply there's nothing...

**Comment by hhuesca** [comment]
Thank you! Found it at: /private/var/folders/73/_m84ymb92wg3m_x09f_rgsl40000gn/T/tmp-114918dweDIeR9wna

**Comment by AbelIngrand** [comment]
You shouldn't take care of where this file is, it is generated by the app and used by Xcode, the path will be different for every user as it is stored in tmp directories.

**Comment by iam4x** [comment]
This is only a warning and should be ignored and @AbelIngrand clarified the issue 👍
