### ISSUE TITLE
LocationSpoof not returning location on 1.0.3

### ISSUE THREAD

**Issue by craigus12** [iam4x/pokemongo-webspoof#106]
Seems to be blank now I have downloaded the latest pokemon go version - definitely was working on 1.0.2
<img width="802" alt="screen shot 2016-07-20 at 21 16 39" src="https://cloud.githubusercontent.com/assets/15033515/17001574/7752e780-4ebf-11e6-9883-2fe83e3434ce.png">

**Comment by Lumerias** [comment]
Same here. If I click the arrow, it puts me out in the Atlantic, west of Nigeria.

**Comment by ferazambuja** [comment]
same here

**Comment by Tjessx** [comment]
Same here, however i didn't download a newer pokemon go version.

**Comment by thomasgrastein** [comment]
Not sure what causes it, but you can still just manually find your location, and when you are there with the pokeball in the app, you can enable autoupdate

**Comment by Lumerias** [comment]
@thomasgrastein anytime I try to type in my location, it gives an error and stays lost in the middle of the Atlantic Ocean.

**Comment by dubert** [comment]
I'm having the same issue

**Comment by ferazambuja** [comment]
For me, after I tried to paste my lat-long it changes to NaN.
Also, it seems to kill the GPS signal on the game (GPS signal not found).
Is anyone able to run it since the update?

**Comment by gere1234** [comment]
Signal's dead

**Comment by ferazambuja** [comment]
??
I close the app and the GPS signal comes back.

**Comment by frandariem** [comment]
Any comments on this issue? It stopped working when they fixed the servers just a few minutes ago.

**Comment by tiagocardosoweb** [comment]
I think the problem might be with Google Maps API.

**Comment by alexpearce92** [comment]
Was working on 1.0.3 last night

**Comment by TCB13** [comment]
I'm getting the same issue here. Also on version 1.0.3.

Additionally I'm unable to set it to any location:

![captura de ecra 2016-07-21 as 05 08 55](https://cloud.githubusercontent.com/assets/6315832/17011038/7d16d40a-4f01-11e6-895f-8968b75a394c.png)

This happens on the coordinates. Thank you!

**Comment by arnaudWasappli** [comment]
Same for me

**Comment by ahmed1993** [comment]
I am running into the same issue.

**Comment by alexpearce92** [comment]
ok, found a short term fix: you will have to look up the GPS coordinates of your current location. Enter the numbers into the lat/lng boxes without deleting the 0 (if you do, you'll be stuck with NaN) that's there by default and without any periods or negative signs. When you have the full coordinate, put in the decimal and negative signs. The default 0 should be erased automatically.

**Comment by ahmed1993** [comment]
Thanks that worked!

**Comment by westlywright** [comment]
So I think i've found another work around. I noticed that after I closed the app that something was still using my location (indicated by the gps icon in my menubar). I dug through system processes and found maps was not running even though the location indicator said maps was the culprit. So I opened maps and quit it. Started the app up again and it all worked. Dont know if this works every time but it's worked a couple times for me.

**Comment by iam4x** [comment]
@alexpearce92 Got a good workaround, this is def a bug will look into it.

**Comment by jhoye88** [comment]
I tried @alexpearce92 workaround, but im not able to punch in any decimals :/ It will only take numbers

**Comment by westlywright** [comment]
@jhoye88 put your cursor at the end of the number and arrow over to where the decimal should be, enter decimal. That worked for me.

**Comment by TCB13** [comment]
Can someone explain my why we can't simply copy and paste GPS coordinates to the App? It would fix the Algolia related issues...

**Comment by tiagocardosoweb** [comment]
@iam4x There is a problem with API Key. Do you know what is happening?

<img width="1279" alt="captura de ecra 2016-07-21 as 23 00 45" src="https://cloud.githubusercontent.com/assets/6529821/17040368/20833ce2-4f97-11e6-9ab4-71c53c19d55f.png">

**Comment by lukesnowden** [comment]
if in england, type a 5 at the begining of the lat and hit enter, will get you to boston. navigate from there

**Comment by TCB13** [comment]
@tiagocardosoweb I don't know how you're getting that error. My google maps seems ok, the only thing failing here is the shitty Algolia API that shouldn't be there in the first place...

**Comment by iam4x** [comment]
Will be fixed in next release with https://github.com/iam4x/pokemongo-webspoof/commit/fab5985769e2e258ad2dbe83373a6c7aef49b8c6

**Comment by iam4x** [comment]
Released https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.1
