### ISSUE TITLE
Map Draggable

### ISSUE THREAD

**Issue by Lumerias** [iam4x/pokemongo-webspoof#107]
You used to be able to drag the map and the pokemon ball would stay centered and the map would move under it. I liked the lock feature (b/c I would accidentally click the map and teleport far away, which got me soft banned), but I loved being able to move the ball anywhere I wanted. Can you add this feature again (with the lock still) so that we can move the ball and wherever the ball lands it asks us if we want to walk, ride, or teleport to that location? If you don't know the exact address of a place, it turns up an error and doesn't give you the option (e.g., Magic Kingdom at Disney World).

**Comment by jninth** [comment]
You can get the Lat and LNG for coordinates from Google Maps.

**Comment by Lumerias** [comment]
Tried that, if you make a mistake and delete it, the coordinate is replaced by NaN and then you can't click on it to correct it.

**Comment by d3viant0ne** [comment]
@jninth  And it doesn't have to be a mistake. The input doesn't debouce and you can't paste into it which means as soon as you come up with an invalid GPS coordinate while typing you get "NaN" and the map is bricked.

NaN is then written to the gpx which in turn also bricks everything running on your phone as well.

**Comment by arnaudWasappli** [comment]
I miss the drag on the map to move the pokemon ball too :(

**Comment by d3viant0ne** [comment]
@arnaudWasappli - Agreed, the locking is a nice feature but no longer being able to drag the ball to an initial starting location before starting up the game is a big hit for usability.

Given you can't reliably search for locations or enter GPS coords, moving the ball is kind of a necessity.

I've personally rolled back to an earlier version for the time being.

**Comment by iam4x** [comment]
Let's keep discussion into #66 👍
