### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by Vedaad-Shakib** [iam4x/pokemongo-webspoof#109]
Many Pokemon Go players have Android devices. Would be nice to get support for that.

**Comment by ferazambuja** [comment]
There are quite a few options for Android users. Nox for PC works really fine.

**Comment by po5i** [comment]
How do you expect that an iOS project have support for Android?

**Comment by jninth** [comment]
You have Nox and Bluestacks for Android devices though...

**Comment by d3viant0ne** [comment]
@Vedaad-Shakib It's an iOS project, the backend would have to be built for Android i.e Java which would be well outside the scope of this. a

**Comment by iam4x** [comment]
I have no knowledge with Android and no devices, if someone wants to add this feel free. For now it's a wontfix.
