### ISSUE TITLE
can you please add 

### ISSUE THREAD

**Issue by g3crossfire** [iam4x/pokemongo-webspoof#11]
- A corner walk arrow.
-having a second .gpx file doing the same auto click update would be a good alternative avoid the error we all get. switching between the two files every 1min will fix the glitch.

**Comment by iam4x** [comment]
I dont get what are you trying to explain, does #10 is addressing the feature?

**Comment by g3crossfire** [comment]
looks like you have fixed the issue in your new update in #10 so this can be closed.
