### ISSUE TITLE
Current location name: Unknown

### ISSUE THREAD

**Issue by dubert** [iam4x/pokemongo-webspoof#112]
<img width="161" alt="screen shot 2016-07-20 at 20 25 08" src="https://cloud.githubusercontent.com/assets/1843672/17007627/56a90f16-4eb8-11e6-8efe-b988e78b6181.png">

It was working for me earlier.. but now I can't get it to detect my current location. Any idea why? Could it be a server load issue?

**Comment by ferazambuja** [comment]
Seems to be the same as this:

LocationSpoof not returning location on 1.0.3 #106
[https://github.com/iam4x/pokemongo-webspoof/issues/106](https://github.com/iam4x/pokemongo-webspoof/issues/106)

**Comment by dubert** [comment]
Yes it is

**Comment by gere1234** [comment]
seems here

**Comment by tiagocardosoweb** [comment]
The problem might be with Google Maps API, It would be better if we can use our own Google API Key and not `yesIWantToUseGoogleMapApiInternals={ true }>`

**Comment by maestroi** [comment]
got same problem, when you switch the debug option of you got gps back, so the app on the phone is interfering with pokemon app?
