### ISSUE TITLE
No GPS signal

### ISSUE THREAD

**Issue by MrMillionDollarSmile** [iam4x/pokemongo-webspoof#113]
Everytime i use this app now, it says that there's no gps signal, and the map doesnt appear on the program

**Comment by tiagocardosoweb** [comment]
Already reported the problem, I'm pretty sure it's a problem with Google Maps API. Already tried to fix the problem but I don't have enough JS experience for fix the problem. Lets wait.

#112 #106

**Comment by Lumerias** [comment]
For me it only happens when I tap on a gym that I'm not close to. As soon as I exit the gym, my avatar stops moving and the No GPS Signal warning comes on. Every. Single. Time.

**Comment by jrudow1** [comment]
I think I might of found the problem and if that is correct what I found I am more then willing to shareit but I don't know how to compile all this to see if my fix worked

**Comment by jrudow1** [comment]
Ill put it here I believe that in the package.json where it says "google-map-react": "^0.15.1”, it should be "google-map-react": "^0.16.0”, but I am not sure I am just taking a shot in the dark on this one because I don't know how to compile it correctly. If this works please let me know and ill upload the new package.json on here

**Comment by d3viant0ne** [comment]
@jrudow1 - A minor version increase denotes no breaking changes according to semver, odds are that isn't going to solve the problem.

**Comment by tiagocardosoweb** [comment]
@d3viant0ne You are right, its only a minor change.

**Comment by ferazambuja** [comment]
By some strange reason now the app is working for me..
Haven't touch a single line of code just tried and failed to run the old version.

**Comment by tranv94** [comment]
For me, it's working for addresses not in the U.S. Currently I'm in Nigeria and it's letting me teleport around.

**Comment by iam4x** [comment]
If the map doesn't shows up, it's an issue with google maps api or your connection. Try again later :(
