### ISSUE TITLE
Pokemon go exits as soon as I enable pokemonLocation

### ISSUE THREAD

**Issue by qitang** [iam4x/pokemongo-webspoof#114]
Pokemon go exits as soon as I enable pokemonLocation. Thanks in advance!

**Comment by Raizelian** [comment]
Before building and running in Xcode, go to View > Debug Area > Show Debug Area.
Observe the box in the right where the little trash can is, does Xcode return some kind of error once you build and run the app?

**Comment by qitang** [comment]
@Raizelian I am not seeing this error after I updated to the lasted version. Thank you anyway!!
