### ISSUE TITLE
location set to 0, 0 on initial launch

### ISSUE THREAD

**Issue by tiasmaiti** [iam4x/pokemongo-webspoof#118]
On initial lauch of the app the location is set to 0, 0. If I try to move manually NaN appears.

**Comment by Niklas420** [comment]
I have the same Problem

**Comment by djadstar** [comment]
Happened to me once, looks like it got me a ban as well.

**Comment by iam4x** [comment]
I should add another destination at first start. It seems like I can't access your geolocation, will add an error message for it.

**Comment by iam4x** [comment]
Will be available in next release 👍

**Comment by iam4x** [comment]
will keep open until next release

**Comment by davinci44** [comment]
got the same proboblem.. worked fine this afternoon but now same problem. does this mean that we won't be able to use this spoof until next update is out?

**Comment by zekkd** [comment]
I got same problem. Has been working flawless for days, but here to night i encounter this problem as well.

**Comment by iam4x** [comment]
Update will arrive tonight. Need another bug fix.

**Comment by davinci44** [comment]
@iam4x Thank you for the fast update! good job 👍

**Comment by iam4x** [comment]
Released: https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.1
