### ISSUE TITLE
The app has finished running

### ISSUE THREAD

**Issue by james-145** [iam4x/pokemongo-webspoof#12]
I've got the app connected and working fine but after anywhere from 3 minutes to 15 minutes it will just stop and display 'the app has finished running in xcode' I'm not sure where any debugs logs are that I can send you.

When the app 'finishes' I get sent straight back to my home location which is bound to cause some alarmbells :)

**Comment by james-145** [comment]
The only issues I have are two warnings -

`The provisioning profile "iOS Team Provisioning Profile: com.nameichose" is expiring soon
`
and

`Warning: skipping file '/var/folders/3q/4lt7sqgd1fj27b6gbwkht8lc0000gn/T/tmp-61155lMmEQI3B4ej4/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)`

**Comment by iam4x** [comment]
I receive the issue also, can you open the Xcode debugger console and see what message do you have when it quits. For instance I have:

```
 Message from debugger: Terminated due to memory issue
```

I don't really know what to do since the app is a blank page ¯\_(ツ)_/¯

**Comment by james-145** [comment]
I have the same

`Message from debugger: Terminated due to memory issue`

Probably a memory leak issue somewhere 

http://stackoverflow.com/questions/19203790/is-it-possible-to-debug-terminated-due-to-memory-error has some suggestions

Apart from this, this is a great app :) really nice work

**Comment by iam4x** [comment]
Thank's to @favret I have enabled background running mode for the app, it should not crash anymore. Will update release today, I want to finish #10 in it also 👍

**Comment by iam4x** [comment]
Released in v1.1.0 https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.0

**Comment by danielsantiago** [comment]
I'm still having the same issue "Message from debugger: Terminated due to memory issue" using the lastest version (v1.1.0), iPhone 6, iOS 9.3.2

**Comment by danielsantiago** [comment]
https://github.com/kahopoon/Pokemon-Go-Controller/issues/21#issuecomment-233827271

**Comment by AbelIngrand** [comment]
Working on this implementation

**Comment by boonaloo** [comment]
I am still having this issue. The app will close with the same memory message.

**Comment by Feri90** [comment]
Step 1 and 2 make sense and I know how to do it. 
But Step 3 and 4 is quite difficult for me. 

I don't know where I can add a silence-MP3 to the project and I can't find ViewController.m
Just another ViewController.swift fil
