### ISSUE TITLE
How to debug Electron?

### ISSUE THREAD

**Issue by eXhausted** [iam4x/pokemongo-webspoof#122]
I'm new to js and Electron setup, but have strong background in iOS dev. Could you explain how to run the app, using **npm run dev** to see console.log from js files?

**Comment by d3viant0ne** [comment]
@eXhausted In the electron menu, open dev tools ( very similar to chrome dev tools ).

**Comment by d3viant0ne** [comment]
You can think of electron as a desktop web app in this case. Debugging is the same as you would a JavaScript web application.

`console.log(things)` and check the output in the tools

**Comment by CrazyJayson** [comment]
Does someone know why the electron app is just blank if I npm run dev?

**Comment by richardjkeys** [comment]
@CrazyJayson Update Node?

**Comment by CrazyJayson** [comment]
@richardjkeys  uhm I don't know what that means :/ Im not a developer (just a little bit swift) what you mean?

**Comment by CrazyJayson** [comment]
npm install looks better now in terminal 👍  I think its gonna work now

**Comment by CrazyJayson** [comment]
its still blank :(
