### ISSUE TITLE
explanation of point 3

### ISSUE THREAD

**Issue by lukesnowden** [iam4x/pokemongo-webspoof#123]
Any chance of elaborating on "Rename the Bundle Indentifer to something unique and different" for those of us who aren't that clever 😂

**Comment by hhuesca** [comment]
You have to change it in the "General" tab, just put any name you like.
![captura de pantalla 2016-07-21 a las 8 49 10 a m](https://cloud.githubusercontent.com/assets/20577711/17025111/183e8dc4-4f20-11e6-9043-b92cd69df7f3.png)

**Comment by lukesnowden** [comment]
That sorted that. It has built onto my device, a white screen appears. When i click "back to P. Go" and move the around on my mac nothing happens on my iPhone, anything I'm missing?

**Comment by Raizelian** [comment]
Have you made sure that Pokémon GO was open before starting the webspoof app on your Mac?
Once the app is running and your phone screen is white, you can just switch to PGO with the multitasking. Then, you just:

> Check the "Auto update Xcode location" option in the Mac app
> Go back to Xcode, go to Debug -> Simulate Location -> pokemonLocation

If the "pokemonLocation" option doesn't appear in that menu, move the map around a bit and check again.
Once that's done, you should be able to move the little pokéball on your Mac and see your PGO avatar moving accordingly.

**Comment by lukesnowden** [comment]
yeah it was the last two, threw a load of errors, something about a menu item, but has suddenly kicked in now! cheers
