### ISSUE TITLE
No movement on phone

### ISSUE THREAD

**Issue by joshmc82** [iam4x/pokemongo-webspoof#128]
I followed directions, but I can't get any movement on my phone. I made sure the app was allowed under Accessibility. (Using Xcode 7.3.1)

Steps I followed:
run Pokemon Go app on iOS
Plug in phone to Mac
Execute webspoof app on Mac
Update Bundle name
From XCode, Select 'Product' -> 'Run'
From webspoof app, click "Auto Xcode Update Location"
From XCode, Select 'Debug' -> 'Simulate Location' -> 'pokemonLocation'
Go back to webspoof, move using on-screen arrows or keyboard arrows
- Ball moves across on-screen map, but nothing on phone at all.

**Comment by d3viant0ne** [comment]
@joshmc82 - Have you also trusted the app on your phone itself?

**Comment by joshmc82** [comment]
I'm unsure what you mean by trusted the app on my phone. Can you clarify/provide instructions?

**Comment by joshmc82** [comment]
I trusted the computer from my phone, if that's what you mean.

**Comment by d3viant0ne** [comment]
@joshmc82 - Yeah `settings/general/Device Management/<team name>` & then `Trust <Team Name>`

**Comment by d3viant0ne** [comment]
Open the dev tools in the electron application and check the console for any errors would be my next suggestion.
![screen shot 2016-07-21 at 11 08 48 am](https://cloud.githubusercontent.com/assets/8420490/17030094/8ea33420-4f33-11e6-872a-901d1a6d3587.png)

**Comment by joshmc82** [comment]
I Don't have "Device Management" under `Settings/General` on my phone.

**Comment by joshmc82** [comment]
Figured out the problem. I had to add my account at the bottom of the bundle thing. Then I had to sign the package or something. Once I did all of that, it let me trust the cert and app on my phone. Now it is working. Perhaps the documentation could be updated to better reflect those steps.
