### ISSUE TITLE
latest update

### ISSUE THREAD

**Issue by g3crossfire** [iam4x/pokemongo-webspoof#13]
was trying your newest update, was being very glitchy. got me soft band.

**Comment by xrolfex** [comment]
Any idea on how long your soft ban lasted.

**Comment by iam4x** [comment]
@xrolfex Try to move slowy arround your area like you were walking and it should not stay long. It happens to me and it stays like 5minutes.

**Comment by xrolfex** [comment]
When I first loaded it it jumped me across the country so it may last longer for me.

**Comment by g3crossfire** [comment]
Lasted 2hr
