### ISSUE TITLE
App Quits Running

### ISSUE THREAD

**Issue by travisfisher** [iam4x/pokemongo-webspoof#131]
I've noticed when running the app that it will quietly quit running and it results in a teleport back to my actual location. It happens every few minutes and it seems to happen a lot when I find a pokemon and I'm trying to catch it.

I'm running XCode 7.

**Comment by zhexuany** [comment]
Same issue here. I thought the team already fixed in current version.

**Comment by d3viant0ne** [comment]
@travisfisher - It's a known issue. Memory leak related to a race condition when writing to the gpx file during rapid movement.

**Comment by d3viant0ne** [comment]
@zhexuany - I'm running a dev build off master & it still happens

**Comment by zhexuany** [comment]
@d3viant0ne  But it got worse than before. For now, it only works for a few minutes even I just open Pokemon Go. Is there a quick fix for this situation? I read the commit history, there is a commit history said resolving this issue by enabling background running. It seems the fix does not work. :(

**Comment by zhexuany** [comment]
The possible fix is to deleting app from the device and build for testing. This fixed my problem.

**Comment by jhoye88** [comment]
I have the same issue. If i move at high speed/teleport frequently, the app will stop running as soon as I encounter a Pokemon trying to catch it.

**Comment by iam4x** [comment]
When you update please delete everything before installing new apps. @jhoye88 the app is not linked to pokemongo it just fakes GPS location of your iOS device. This is a bug with pokemongo app itself.
