### ISSUE TITLE
Enable pin drop for autopilot

### ISSUE THREAD

**Issue by Juank1995** [iam4x/pokemongo-webspoof#132]
There should be a pin drop to set the autopilot, not only places that apear in the searchbox. People who live in rural areas do not have any or few places from the Algolia search near to use this function.

**Comment by d3viant0ne** [comment]
@Juank1995 - I was just pondering that as a feature myself. I'm more of an angular guy than react guy but I'm probably going to take a stab at adding it as a feature. Also solves the problem of no longer being able to drag the ball.

Assuming of course that @iam4x doesn't already have this in the works.

**Comment by ferazambuja** [comment]
Actually, Algolia seems to be not that reliable with US maps.
Try different city names for the address result that you are looking for. Usually the strange ones.
The pin drop might fix the need to change for google maps.

**Comment by d3viant0ne** [comment]
More of a work around than a fix but for moving around in a known location, i.e. the city in which you live I feel it would be a useful addition.

**Comment by nickg819** [comment]
Or "favorite" addresses. That way you can store a location like work or home in the app.

**Comment by iam4x** [comment]
Feature planned, continue discussion into #59
