### ISSUE TITLE
"..."pokemonLocation.gpx" is invalid."

### ISSUE THREAD

**Issue by zoofo** [iam4x/pokemongo-webspoof#134]
Hello!

When I click the "PokemonLocation" I get an error that says: "Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid."

I haven't been able to see any map either, how can I get the map to appear?

Thanks in advance!

**Comment by d3viant0ne** [comment]
As to your first issue, you need to turn on `Auto Update Xcode Location` and move once to get the geolocation written to the .gpx file.

As to your second issue, the latest release version has the geolocation set to 0 / 0 which isn't valid. That then gets written to the gpx file and nothing works.

**Comment by zoofo** [comment]
Thanks for the quick response! 👍 

I am a big newbie but I have been trying to check most of the posts here and on reddit but cant understand where I find the option to turn on "Auto Update Xcode Location".

perfect, so my second issue will be solved once I turn on "Auto Update Xcode Location". Will the map show up then as well or do I have to click on something for it to appear?

Thanks again!

**Comment by munq** [comment]
![its here](https://cloud.githubusercontent.com/assets/685894/17033277/fa71bf24-4faf-11e6-8dc7-ec9c585866db.jpg)

**Comment by zoofo** [comment]
@munq How do I even get that map to appear? as for now I am trying to find some sort of button to open it in xcode but I am not doing well... How do I get that map/"pokemon go - location spoof" to open? :)

**Comment by iam4x** [comment]
Sometimes it happens, please look https://github.com/iam4x/pokemongo-webspoof/issues/125#issuecomment-234368037
