### ISSUE TITLE
Unable to Teleport outside of US

### ISSUE THREAD

**Issue by fkick** [iam4x/pokemongo-webspoof#135]
When attempting to search for a location outside of the US, I get a "Zero_results" error. Was hoping to use it to teleport to London (after staying offline for a while, simulating a plane trip) and got the error.

**Comment by munq** [comment]
I believe the error lies in the Autopilot looking for a route before displaying the options thus throwing the error. You can get around this by manually entering the GPS coordinates. You might have to highlight and change the numbers before and after the decimals as I'm having issues entering the decimal place.

**Comment by ag9710** [comment]
Don't do it !
I got banned because of that :(

**Comment by iam4x** [comment]
Should not be doing that, but there's an issue to re-enable it #62
