### ISSUE TITLE
Skipping file pokemonLocation.gpx - unexpected file type

### ISSUE THREAD

**Issue by wwwchrisde** [iam4x/pokemongo-webspoof#136]
When I try to run the app - I get the following error message - the app on iPhone just shows a blank white page. How do I resolve this issue? 

warning: skipping file '/var/folders/j1/jh2h1r_s7gb2s9_chxdt6jdr0000gn/T/tmp-44107Cy5uEW6wK2B/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

**Comment by iam4x** [comment]
It's only a warning and can be ignored, look https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874
