### ISSUE TITLE
Working fine but can't catch pokemons or take pokestops?

### ISSUE THREAD

**Issue by f1rren** [iam4x/pokemongo-webspoof#137]
Hey,

Got mine working fine, but it seems like I can't catch any pokemons or take any pokestops. Pokemons are fleeing after every first catch attempt, even tho I use berrys and great balls. 

Can someone help me out?

**Comment by munq** [comment]
From the README

"NOTE: To avoid being soft banned, don't change your location to fast: the ban is issued if the server sees you traveling a too long distance in a short amount of time."

  Refer to this other closed issue. #24
