### ISSUE TITLE
How to "Auto Update X-Code Location"?

### ISSUE THREAD

**Issue by zweiss438** [iam4x/pokemongo-webspoof#138]
I can't find the option anywhere, thanks.

**Comment by saygun** [comment]
👍

**Comment by munq** [comment]
![its here](https://cloud.githubusercontent.com/assets/685894/17033302/17f9af98-4fb0-11e6-8263-e34860d7eed5.jpg)

**Comment by zweiss438** [comment]
I don't have the screen on the mac, should it automatically open?

**Comment by zhexuany** [comment]
@zweiss438  How do you build your software? Did you download from release or you build on yourself. You should run `npm run lint` first.

**Comment by zweiss438** [comment]
@zhexuany I downloaded it today

**Comment by zoofo** [comment]
I have the same issue, cant seem to find the "map" window/program... I downloaded the zip and unzipped it, connected my iphone and started "pokemon-webspoof.xcodeproj". xcode starts and the build is successful, I run the scheme and my iphone changes window into the new app, I click launch and I return to pokemon go. From here on nothing is happening, how do I get the map to appear?

**Comment by zweiss438** [comment]
Exact same process for me

**Comment by z888** [comment]
Took me a moment to figure it out too... But you don't want to download the GitHub file.. Instead there's a link in the read me section after the image.. It Says download latest release

That's the file you need to download and open, the rest of the instructions should make sense after that

Hope that helps

**Comment by zweiss438** [comment]
Thank you, that was way simpler the I thought

**Comment by iam4x** [comment]
Thank's guy for the support 👍  I'll close this ;)
