### ISSUE TITLE
Map not work

### ISSUE THREAD

**Issue by giacomoalonzi** [iam4x/pokemongo-webspoof#140]
Hi, in the mac app sometimes the map is not shown properly. 
https://infinit.io/_/3jVDCus

**Comment by zoofo** [comment]
How did you get the app? :)

**Comment by giacomoalonzi** [comment]
@zoofo from github, yesterday and today worked fine.

**Comment by zoofo** [comment]
Which program/file do you click to open the map? I can't seem to get it open...

**Comment by jhoye88** [comment]
I have the same issue, just started 30 minutes ago, have been working fine all day.

**Comment by soroshd** [comment]
Same here...

**Comment by pawelkolanowski** [comment]
+1

**Comment by tiagocardosoweb** [comment]
Same problem here.

**Comment by Talhabestaz** [comment]
same here

**Comment by zweiss438** [comment]
same

**Comment by djadstar** [comment]
Also having this issue

**Comment by StefanMeGit** [comment]
same here... worked fine in the morning, but now its broken...

**Comment by DavydeVries** [comment]
I think the rate limit of the google maps api is reached....

**Comment by jhoye88** [comment]
@DavydeVries Yeah something seems to be disturbing the Google Maps API, so you're probably right.

**Comment by osxdoc** [comment]
Same here

**Comment by lecramr** [comment]
I don't think it's the GMaps Api.. If you press any arrow key, the coordinates will change and the map will load. So I think the Error is the Geocoder Api, I'll have a look at it later..

**Comment by lecramr** [comment]
@zoofo https://github.com/iam4x/pokemongo-webspoof/releases/download/v1.1.0/pokemongo-webspoof-v110.app.tar.gz for Mac only

**Comment by c0de** [comment]
its having problems loading the KML and timing out on @action handleGoogleMapLoaded. Not loading the pokemon spots map fixes it.

**Comment by ferazambuja** [comment]
Can we merge the tickets? 
#106 #113 #118 #133
Are all about the same issue.

**Comment by Humanboss** [comment]
Also receiving this problem. Was just walking around town and then lost my gps signal. Restarted my phone, the computer and reinstalled the app. Nothing worked.

**Comment by Lumerias** [comment]
Ok, so I posted over in the No GPS Signal thread that got linked here. I noticed that everytime I lose GPS signal, it says 'Finished running pokemon-webspoof on iPhone 6 Plus' in the Xcode. It keeps stopping. Why is this? What is causing it to stop running? If I open up the task menu on my iphone to see what is running in the background the spoof app is still there running.

**Comment by Lezul** [comment]
Just installed 1.1.0. Same problem here.

**Comment by tiagocardosoweb** [comment]
If thats a problem with Google API reaching the requests limit, would it be possible to us add our own Google API Key?

**Comment by xDae** [comment]
+1

**Comment by iam4x** [comment]
@c0de Will remove it, it's kinda useless anyway track this here: #54 

@tiagocardosoweb Google Maps it's not shared between users, it uses your own connection directly. So no need for Google API Key 👍 

Please continue discussion into:

* https://github.com/iam4x/pokemongo-webspoof/issues/118
* https://github.com/iam4x/pokemongo-webspoof/issues/106
