### ISSUE TITLE
Where is Auto X-Location? My map doesn't show up?

### ISSUE THREAD

**Issue by maegen** [iam4x/pokemongo-webspoof#143]
Where does the map come up and when I do the PokemonLocation.gpx it says its **invalid**, so I tested NYC and it worked but then I couldn't move because the map doesn't show up?

**Comment by maegen** [comment]
<img width="1278" alt="screen shot 2016-07-21 at 2 18 51 pm" src="https://cloud.githubusercontent.com/assets/20585585/17037439/286f7590-4f4e-11e6-972b-636325cffc47.png">

**Comment by zoofo** [comment]
Install the app from here: https://github.com/iam4x/pokemongo-webspoof/releases/download/v1.1.0/pokemongo-webspoof-v110.app.tar.gz

That should do it :)

**Comment by djadstar** [comment]
Lot's of issue logs about this, is being worked on!

**Comment by maegen** [comment]
I tried downloading the latest version above and it is not functioning it just closes or doesn't open at all or shows a blank screen.

**Comment by iam4x** [comment]
Should be fixed in last release https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.0
