### ISSUE TITLE
update

### ISSUE THREAD

**Issue by pvemedia** [iam4x/pokemongo-webspoof#145]
if i download the update u make about the speed. 
and copy the files inside the the app its not working.
do i something wrong.

**Comment by tranv94** [comment]
This is really vague. Are there any errors showing?

**Comment by pvemedia** [comment]
no there are no errors. everything is working. if i use the auto navigation then i can walk only in 12km/h. 
i wait until the next release is to try that one.

**Comment by evannudd** [comment]
The updates that you're seeing in the commit log are updates to the code base, this does not directly represent the .app that is currently available for download. These updates will eventually be made into a new .app and will be released (probably under the version 1.2?)

**Comment by yformaggio** [comment]
You can use the [dev version of the app](https://github.com/iam4x/pokemongo-webspoof#develop) after checking out the repo if you wanna use the bleeding edge features
