### ISSUE TITLE
xCode 8 beta 3 - autoclick not working - crash xcode

### ISSUE THREAD

**Issue by DavydeVries** [iam4x/pokemongo-webspoof#146]
If I turn on autoclick, xcode 8 beta 3 will crash. Should I use another xCode instead?

**Comment by AbelIngrand** [comment]
You should use the latest stable Xcode version, except if you're running iOS 10 in which case it won't work (only works with Xcode 8)

**Comment by evannudd** [comment]
IOS 10 does work with Xcode-beta.

**Comment by AbelIngrand** [comment]
Yes, that's what I meant: if he's running iOS 10 he won't be able to run the app with an Xcode version < 8 which is currently in beta

**Comment by DavydeVries** [comment]
To get things straight:
- MacOS Sierra 10.12 bèta (16A254g) (public beta 2)
- Xcode Version 8.0 beta 3 (8S174q)
- iPhone 6 Plus iOS 10.0 (14A5309d) (public beta 2)
- pokemongo-webspoof 1.1.0

I will try the 1.1.1 release now

**Comment by AbelIngrand** [comment]
I believe this is a bug in Xcode beta. Can you try to catch the crash log in the Console app (in Utilities folder) ?

**Comment by DavydeVries** [comment]
Nope, 1.1.1 same problem.

After enabling`Auto update Xcode location` I get a beachball if I hover Xcode (some memory issues on beta?)
So Xcode will be not responding to the applescript/autoclick:
<img width="310" alt="schermafbeelding 2016-07-22 om 09 47 57" src="https://cloud.githubusercontent.com/assets/7860305/17050109/6cca45aa-4ff1-11e6-9975-4d2094de8e56.png">

**Comment by AbelIngrand** [comment]
Ok, try this: Right click on pokemongo-webspoof.app > Show package contents. Navigate to Contents > Ressources > app and open autoclick.applescript.
Replace `Xcode` in `tell application "System Events" to tell process "Xcode"` by the name of the Xcode beta app (something like Xcode Beta or Xcode-beta, can't remember)

Tell me if it works

**Comment by DavydeVries** [comment]
I tried some things like `Xcode`, `Xcode-beta`, `Xcode beta`, `Xcode 8`, `Xcode8`. But no results. 
In the activity monitor the Xcode process is called `Xcode` so I think it's an bug in macOS beta.
<img width="719" alt="schermafbeelding 2016-07-22 om 10 36 54" src="https://cloud.githubusercontent.com/assets/7860305/17052018/ebecedec-4ffb-11e6-8eaf-e33d4f5c7e38.png">

***
This time I looked specially in de activity monitor (with the original script in the app).
And activate `Auto update Xcode location` the CPU usage goes to 50% and the beachball appears in Xcode when I hover it. I think Xcode is don't respond after x times applescript, what caused the error "code 2"

**Comment by AbelIngrand** [comment]
OK, thanks for your help, seems like a bug in Xcode beta..

**Comment by Darkbladecr** [comment]
I am using XCode beta 8c with my iOS10 public beta 2 and it works fine.
I will sometimes get the autoclick error, but usually I can bypass by toggling the autoupdate location.
Sometimes Xcode may prematurely finish running the application so you may lose connection for the GPS coordinates.

**Comment by iam4x** [comment]
I'm using last beta and I don't have any issues, seems more a bug with Xcode itself

**Comment by KoetseJ** [comment]
Also running latest beta, is working fine here.

**Comment by anushkmittal** [comment]
@iam4x  I still can't seem to get it working with Xcode 8. Can you help me with it? 
First, I launch the Mac app and then quit Xcode 7.
Next, I use Xcode 8-beta to launch the project and run it on my iPhone
Even after changing location or doing anything, the auto-click doesn't work and the GPX file is empty which I even corrected with some dummy coordinates but to no success.

Do you know what's happening here?

make some movement on

**Comment by KoetseJ** [comment]
Oke you are probably selecting the gpx file wrong, use the bar in the top
of the screen and select debug -> then location something, and under there
select the GPX file.

Op maandag 25 juli 2016 heeft Anushk Mittal <notifications@github.com> het
volgende geschreven:

**Comment by DavydeVries** [comment]
Solved after macOS public beta 3 and Xcode 8 beta 4
