### ISSUE TITLE
Skipped File

### ISSUE THREAD

**Issue by meckin** [iam4x/pokemongo-webspoof#15]
Sorry, I'm not super techie on this subject more of a php guy being a marketer (i know im a sad soul), but anyone can help me with this?

Warning: skipping file '/Users/name__/Desktop/pokemongo-webspoof-master-1/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

**Comment by iam4x** [comment]
This is known issue, dup of #4 

Easy fix: Click "auto update Xcode location" then move once, it will write the `pokemonLocation.gpx` missing file. Don't worry if there's an error in the app it's normal.

Then you will be able to build on your iPhone.

If you still have problems be sure to read https://github.com/iam4x/pokemongo-webspoof#known-issues

**Comment by meckin** [comment]
Seems like the file is skipped, even thought I'm seeing the file now.

**Comment by iam4x** [comment]
Can you attach a screenshot of the issue? I don't get it :/

**Comment by james-145** [comment]
It seems the file is generated when the program runs, the error is just a warning and the program compiles and runs normally.

**Comment by iam4x** [comment]
Continue discussion into #4 

It will be fixed in next version 👍
