### ISSUE TITLE
Can't catch Pokemon or use Pokestops when far away from my actual location

### ISSUE THREAD

**Issue by karlmonson** [iam4x/pokemongo-webspoof#151]
I live in Utah, and for the most part I can auto-walk and catch Pokemon just fine around my town. But for example I teleport to Santa Monica Pier and without fail every Pokemon I try to catch breaks out of the ball and runs away. Also, I can spin Pokestops but will not get any items when far away from home. This seems like odd behavior, and I don't know if there is a fix for this, but it seems like a bug.

**Comment by 1YKM** [comment]
You've soft banned, be careful because can get perm banned. Make you sure read the README

> **NOTE:** To avoid being soft banned, don't change your location to fast: the ban is issued if the server sees you traveling a too long distance in a short amount of time

**Comment by iam4x** [comment]
Duplicated, read the known issues.
