### ISSUE TITLE
New release not wanting to open 

### ISSUE THREAD

**Issue by derpsoul** [iam4x/pokemongo-webspoof#153]
on el captain 10.11.16, it shows the blue app icon in the dock, waits a bit, doesn't open xcode and then it just closes...any ideas?

**Comment by digitalknk** [comment]
I have the crash report here if you would like to see it.

[https://goo.gl/gjRHTK](https://goo.gl/gjRHTK)

**Comment by derpsoul** [comment]
worked after i redownloaded and repeated the instructions on updating, i may have jumped some steps

**Comment by Nozk** [comment]
I'm having the same error as derpsoul, followed the instructions. Removed everything(including security), then re downloaded, then added security access. Still the program does not open.
