### ISSUE TITLE
Failed to code sign "pokemon-webspoof".

### ISSUE THREAD

**Issue by pvemedia** [iam4x/pokemongo-webspoof#16]
Cant get the app running. if i press build & run it come with the error
Failed to code sign "pokemon-webspoof".

i try to fix it but will not work.

**Comment by zasaar** [comment]
I get the same error every time.

**Comment by james-145** [comment]
Just rename the bundle identifier to something random

**Comment by iam4x** [comment]
Or sign code with an apple developer account

**Comment by zasaar** [comment]
both don´t work for me
<img width="1280" alt="bildschirmfoto 2016-07-17 um 20 28 12" src="https://cloud.githubusercontent.com/assets/20504491/16902368/21b6dcd2-4c5d-11e6-888c-6deeae2c7511.png">

**Comment by james-145** [comment]
thats a different issue, just click fix issue

**Comment by zasaar** [comment]
sry wrong pic
<img width="1280" alt="bildschirmfoto 2016-07-17 um 20 31 55" src="https://cloud.githubusercontent.com/assets/20504491/16902405/c684869c-4c5d-11e6-84e2-4adea595bd99.png">

i don´t have a developer account and i´m logged in with my normal apple id

**Comment by james-145** [comment]
What happens when you click fix issue?

**Comment by zasaar** [comment]
this error comes up
<img width="1279" alt="bildschirmfoto 2016-07-17 um 20 36 17" src="https://cloud.githubusercontent.com/assets/20504491/16902418/4325a276-4c5e-11e6-8a77-330da28efed7.png">

**Comment by pvemedia** [comment]
i have the same as zasaar

**Comment by zasaar** [comment]
someone have the same in issue #18

**Comment by james-145** [comment]
again. you just need to rename the box which says bundle identifer to something different, just mash the keyboard for a few random letters

**Comment by pvemedia** [comment]
thank u that works

**Comment by bello356** [comment]
When I do all of that I get a "No devices. Creating a profile requires having a device registered in Member Center."

I tried doing this but have failed

**Comment by muescha** [comment]
@bello356 its not a solution and not a answer to your problem - it is just a github reference to this issue from an other issue ( click on the link to see the other issue)

to get most possible help describe your problem detailed. (hint: google for the exact error messages to get faster solutions)

**Comment by bello356** [comment]
@muescha 
I googled it several times already, with and without quotes for exact searches 
Everything I've found seems to be very outdated. The apple developer website updates and the links / methods to fix the issue are no longer available 

Did you find anything by doing so?

**Comment by muescha** [comment]
please open a new issue for your problem - it is a different error than in this issue

**Comment by bello356** [comment]
I did right here

https://github.com/iam4x/pokemongo-webspoof/issues/69

But it hasn't been solved yet
