### ISSUE TITLE
Hello Im new to git hub and x code but when ever I simulate location it does this!

### ISSUE THREAD

**Issue by TihBug** [iam4x/pokemongo-webspoof#160]
<img width="1382" alt="screen shot 2016-07-21 at 9 46 31 pm" src="https://cloud.githubusercontent.com/assets/20579667/17044285/c6412a8c-4f8c-11e6-8a4e-a9151237813a.png">

**Comment by coding102** [comment]
You need to use the terminal, move to the folder directory, in the terminal do npm install, and then do npm run dev to run locally.  Xcode should automatically open for you along with the window to control movement and location.

**Comment by hbruno1010** [comment]
@coding102 I don't fully understand what you mean by that and I'm experiencing the same issue as above

**Comment by TihBug** [comment]
@coding102 I know Im kind of being a pain in the ass but if you could show me a clip of you doing it it would be marvelous!

**Comment by AbelIngrand** [comment]
Please see https://github.com/iam4x/pokemongo-webspoof/issues/172#issuecomment-234484080
