### ISSUE TITLE
Working fine but...

### ISSUE THREAD

**Issue by coding102** [iam4x/pokemongo-webspoof#165]
I got it to work and move around with the keyboard but for some reason "stops" don't hold any prizes and pokemon get away from me every time even the weak ones.

**Comment by cheeseonhead** [comment]
You got soft banned haha, just have to wait some hours

**Comment by coding102** [comment]
Can I use the transport function on the app to take me to another location on the map immediately or will that get the soft ban

**Comment by digitalknk** [comment]
@coding102 you can not transport instantly to a far location.

**Comment by coding102** [comment]
^ I was playing in New York City when I was in Philadelphia.  When you add the address you have the option of walking, car , bus , train, or to  instantly be there.

**Comment by AbelIngrand** [comment]
As mentioned in the Readme, avoid using teleport as it will get you soft banned.
