### ISSUE TITLE
"Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid."

### ISSUE THREAD

**Issue by hbruno1010** [iam4x/pokemongo-webspoof#168]
I attempt to do Debug -> Simulate Location -> pokemonLocation and I'm met with an error message that reads "Failed to parse gpx file" and I cannot get anything to pop up past that point, I've seen other help topics but all the fixes seem to be for when you can open the gps on the computer, and i cannot get to that point

I'm wondering what the fix is.

[http://imgur.com/gallery/NSmwL](url) (photo of error message, you have to copy and paste the url, seems like for some reason the link is not just clickable at least in my attempts)

**Comment by phreaky1234** [comment]
Having the same issue

**Comment by CrazyJayson** [comment]
same for me

**Comment by hbruno1010** [comment]
i figured it out, i just wasnt running the .tar.gz file

**Comment by phreaky1234** [comment]
How do you run that file? I downloaded the zip and I don't see a file ending with .tar.gz?

**Comment by phreaky1234** [comment]
oh ok its a separate file

**Comment by ilias412** [comment]
@hbruno1010  hey, where do i find the file you were talking about?
