### ISSUE TITLE
white screen after building and running app

### ISSUE THREAD

**Issue by yeohs** [iam4x/pokemongo-webspoof#17]
After building and running the app on my iOS device, it just takes me to a white screen that doesn't load.

**Comment by yeohs** [comment]
Due to this issue, I'm unable to check the Auto update Xcode location

**Comment by iam4x** [comment]
It's totally normal, keep the "white screen app" running in background and switch to Pokémon Go 👍

**Comment by yeohs** [comment]
After switching back to Pokémon Go, there's no option for me to check the auto update Xcode location.

**Comment by james-145** [comment]
the auto update xcode location is located in the osx app
