### ISSUE TITLE
Location GPX File Invalid

### ISSUE THREAD

**Issue by JamesSimpson** [iam4x/pokemongo-webspoof#172]
Just downloaded the latest version and I'm struggling to get it working with location services. When going into Debug > Simulate Location > PokemonLocation I get the following error message

Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid.

Failed to parse GPX file (/Users/....../pokemongo-webspoof-master/pokemonLocation.gpx)

**Comment by AbelIngrand** [comment]
Try moving a little on the app before simulating location.

@iam4x Do you think we could change the app so that once it figures out the location at launch it generates a first gpx before moving with the keys ?

**Comment by JamesSimpson** [comment]
@AbelIngrand  - I fail to get the actual map to open up at all. I've built the code onto my iPhone, it runs on the iPhone but nothing else happens on my MacBook at all.

**Comment by AbelIngrand** [comment]
Do you have the latest version of webspoof app ? There's a fix for the blank map in 1.1.1

**Comment by JamesSimpson** [comment]
@AbelIngrand - Just downloaded it, works now... Trying the simulating location fix stated above now.

**Comment by JamesSimpson** [comment]
@AbelIngrand - I can confirm your fix works, move a little bit on the map before then going and changing the location service. Perfect 👍
