### ISSUE TITLE
GPS Stuck at location

### ISSUE THREAD

**Issue by kreynes** [iam4x/pokemongo-webspoof#175]
I've used the webspoofer for a bit, got tired of pokemongo. After a while I needed to use the iPhone maps, but apparently my GPS still thinks im stuck at the last location i've used with the web spoofer. No idea how to fix that.

**Comment by Mardaneus86** [comment]
Check issue #45, I guess this is related.

Rebooting your phone might help.

**Comment by AbelIngrand** [comment]
A fix is coming. For now, reboot your phone.
