### ISSUE TITLE
Not working any longer

### ISSUE THREAD

**Issue by vlar** [iam4x/pokemongo-webspoof#177]
Hey I'm facing an issue 👍 
It says

Autoclick.appless
Error in Event Systems :  Osascript Not allowed in a help access (-1719)

the only way i can make partially work is to set a location and then in Xcode debug menu simulate location. And there is works, but can't move at all. 

It used to work perfectly fine this morning. 

Great job anyhow this app is huge!

**Comment by AbelIngrand** [comment]
Please see https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233106899
