### ISSUE TITLE
Memory issue on 1.1.1

### ISSUE THREAD

**Issue by craigus12** [iam4x/pokemongo-webspoof#178]
Everything seems fine but every so often Xcode seems to return this error and stops running:

2016-07-22 14:28:08.601 Pokemon WebSpoof[5563:503393] Received memory warning.
Message from debugger: Terminated due to memory issue

I have "Keep app running in the background" checked and have 8GB of RAM on my MB Pro, currently there's about 6GB used so still have 2GB to play with.

However, it seems much more stable than the previous version. Really great app guys, thanks.

**Comment by AbelIngrand** [comment]
The memory issue is from the iPhone, not the Mac. It's a known bug, it's been fixed in the code and will be a shipped in 1.1.2. See #121
