### ISSUE TITLE
XCode error; cant run the app

### ISSUE THREAD

**Issue by dannyhtek** [iam4x/pokemongo-webspoof#18]
Hey,

I've been following the steps properly but I cant get Xcode to run the app. I'm getting the following error when pressing on the play button:

> "Failed to code sign "pokemon-webspoof.
> No non–expired provisioning profiles were found.
> 
> Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles."

Clicking on the Fix Issue button makes me select a Development team. Choosing for personal team wont work either and gives me the following error: **An App ID with Identifier 'com.iam4x.pokemon-webspoof' is not available. Please enter a different string.**

Any ideas?

**Comment by iam4x** [comment]
Rename the app id identifier to something else that will match your provisioning profile 👍

**Comment by muescha** [comment]
can the app not create a random identifier (UUID) and update the xcode project files before it opens the project in xcode?

**Comment by muescha** [comment]
created a new issue #85 for the idea

**Comment by ksulli10** [comment]
I have the same issue AFTER renaming the Bundle Identifier.  Any ideas?
