### ISSUE TITLE
Pokemon run after 1 attempt to catch them .

### ISSUE THREAD

**Issue by kylelol** [iam4x/pokemongo-webspoof#180]
Every time I go to catch a pokemon, if I don't catch it on the first ball, the pokemon always runs away from me. I assume this is happening because of the reset back to current location bug that other people are reporting. Anyone else getting similar results?

**Comment by avnonline** [comment]
I believe this is the soft-ban. If you're moving too far and too quickly. You're going to run into this for a short amount of time.

**Comment by kylelol** [comment]
Ah so is there a work around? Switch to a location and wait 5 minutes to start moving around?

**Comment by d3viant0ne** [comment]
@kylelol - A soft ban is hours to days. IMHO it is imperative that this is used like you are actually walking around. If you want to bounce locations, close pogo, change locations in spoof, go make coffee, hit the head & open pogo again.

The more "believable" you locations swaps are, the better off you will be. Their banning is only going to get smarter / harsher as time goes on.

**Comment by d3viant0ne** [comment]
It is also possible you are trying to catch a 'mon that's 800cp with a regular ball but i'd bet on soft ban. ^^ See above.

**Comment by jhoye88** [comment]
IMO this is very common when you teleport to a new place. It seems the further you teleport, the longer you have to wait before you can catch pokemons and take pokestops. I usually just port 10km away in my city, and that takes 2-3 minutes before i can catch again.

**Comment by Lumerias** [comment]
When you want to transport somewhere else, just look up how long it would take to get there by plane, train, automobile, etc. Then wait that long before opening the pogo app and then set your spoof to that location and open up the app. You will not be soft banned. I've done this countless times. You CANNOT however be in Nebraska playing pogo and then decide to check out Central Park in NYC, even if you close out pogo, and restart it. Usually, I pick a different location each day and start it there and play ONLY there for that day, my sleeping time is my "traveling" time to the next destination.

**Comment by iam4x** [comment]
There's already a lot of issues on this subject, it's a wontfix 👍
