### ISSUE TITLE
Suggestions: Improvements

### ISSUE THREAD

**Issue by tiagocardosoweb** [iam4x/pokemongo-webspoof#181]
Add a close button into autopilot modal.
Make speed random: if walk max is 9 km/h, make it random between 0 and max.

**Comment by d3viant0ne** [comment]
The discussion around autopilot improvments is happening in #42

**Comment by iam4x** [comment]
* [x] Auto-close modal released into v1.2.0
* [ ] random speed -> already issues for it thank's #42
