### ISSUE TITLE
System Events got an error: osascript is not allowed assistive acces (-1719)

### ISSUE THREAD

**Issue by Juank1995** [iam4x/pokemongo-webspoof#186]
When I try to move this error keeps coming up. To make it work i have to move to a specific point where i want to go in the map then go to Xcode, debug, simulate location, pokemon go location. Don't know if it's of any relevance but this happened while simulating the location in a different country.

**Comment by rjanja** [comment]
You need to go into System Preferences, Security & Privacy, Privacy tab and add the .app to the list there. Otherwise it is not allowed by the operating sytem to execute the AppleScript that controls Xcode.
