### ISSUE TITLE
Error with schedule since OS X 10.11.6

### ISSUE THREAD

**Issue by sle84** [iam4x/pokemongo-webspoof#189]
Since updating OS X to 10.11.6 choosing a destination always results in an error with schedule ZERO_RESULTS (v. 110). V 111 is not even starting. Any Ideas?

**Comment by Map2k** [comment]
I'm on 10.11.5 and same issue appears, so guess it's something else

**Comment by nickg819** [comment]
Did you try updating to OSX 10.12?

**Comment by rjanja** [comment]
Version 1.1.1 addresses a possible Google Maps Geolocation API failure by providing an alternate way of finding location (ipinfo.io). Recommend you build 1.1.1 or apply the same change (fab5985769e2e258ad2dbe83373a6c7aef49b8c6) locally. You could also just hardcode a starting location.
