### ISSUE TITLE
Close Autopilot Window

### ISSUE THREAD

**Issue by Juank1995** [iam4x/pokemongo-webspoof#191]
If you choose a mistaken location you can't close the autopilot window, the only way is to chose any option, except teleport, and as soon as it begins you stop it. Nothing mayor but i guess its something easy that could enhance the app. Great work by the way

**Comment by Wyallat** [comment]
Yes, there is no close button.

**Comment by TCB13** [comment]
+1 on this feature! Thanks

**Comment by iam4x** [comment]
Released in v1.2.0 👍
