### ISSUE TITLE
PokemonGO app in my phone - doesn't receive the GPS updates

### ISSUE THREAD

**Issue by eranb** [iam4x/pokemongo-webspoof#193]
Hi,
I'm trying the use the app with no luck, I downloaded the latest release v.1.1.1 and followed the instructions in the README.

I successfully launch the OS-X-APP + XCODE, build & run the project without any errors.
When I move my location in the app, Pokemon GO in my phone isn't receiving those changes and don't update his map.

When I use the simulator and open Apple map app, it see the right custom GPS values from the webspoof app and the map get update when I move in the webspoof APP.

Spec
```
El Capitan - 10.11.5
Iphone 6 running iOS 9.2.1
Simulator Version 9.3 (SimulatorApp-645.9 )
XCode 7.3.1
```
Any ideas ?

**Comment by jninth** [comment]
Did you add pokemongo-webspoof.app to authorized apps in Accessibility?

    (System Preferences -> Security & Privacy -> Privacy Tab -> Accessibility)

**Comment by eranb** [comment]
@jninth yes I did

**Comment by Lynxdragon** [comment]
Did you turn on simulation from the Debug Menu? It does not work if you use the simulate location from the bottom of xCode.

Usually my process is, Launch Webspoof, Go into xCode and set the correct bundle id, close all apps on my phone, build+run on xcode, turn on auto update xcode location in webspoof, then go Debug > Simulate Location > pokemonLocation, Then open maps on your phone and make sure you have moved on maps, then load pokemon go.

**Comment by eranb** [comment]
Thanks @Lynxdragon,
I just tried it with no luck, I followed your steps, before I opened PokemonGO, I opened the Maps app on my phone and it didn't moved when I change my location in the webspoof app.

I closed all the apps on my phone before I started it, build & run was success without errors, and set the simulate location trough the Debug menu in XCode

**Comment by huihuang** [comment]
Did you turn on  "Auto update Xcode location"?

**Comment by Spatch1** [comment]
Do this before you change the build name
Xcode > Product > Destination > 'YOUR PHONE NAME'

**Comment by eranb** [comment]
@Spatch1 that does the trick!
Thanks a lot guys :)
