### ISSUE TITLE
[BUG] 1.1.1 can't drag map

### ISSUE THREAD

**Issue by wxrdn** [iam4x/pokemongo-webspoof#196]
after update to 1.1.1, the map is not draggable any more.
Also the map in old versions now doesn't work, map won't load and can't enter lag and lon

**Comment by syeom** [comment]
I also cannot drag in 1.1.1

**Comment by Wyallat** [comment]
Yep, map not can't be dragged.

**Comment by TCB13** [comment]
+1 on dev-master.

**Comment by g3crossfire** [comment]
So how do you fix it?
@tcb13 I'm not sure what that means.

**Comment by TCB13** [comment]
@g3crossfire means that I've the same problem as everything above at dev-master.
The only current fix is to downgrade do version 1.0.1.

**Comment by iam4x** [comment]
Fixed into v1.2.0 👍
