### ISSUE TITLE
Finished Running on iPhone issue

### ISSUE THREAD

**Issue by syeom** [iam4x/pokemongo-webspoof#197]
I am able to run the pokemongo-webspoof fine but after a while, the app running in xcode stops with message "Finished Running on iPhone" and my gps stops spoofing and teleports me to my real gps location.. I get soft-banned for this everytime. Please help!!

**Comment by Wyallat** [comment]
Exactly. One of the biggest issues right now. One way to prevent this is to end every app running in the background every once and a while. BUT this is just annoying. I want to walk with the autopilot without having to be present. Yesterday I was in Australia (after 2 hours of softban) and wanted to start collecting some Pokémon . I walked around (by myself) and then BOOM "finished running". 
Is there NO WAY to prevent that from happening?

**Comment by z06jaz** [comment]
Can you guys test something for me? When that happens again and you get teleported back to your current location immediately close the pokemon go game app on your phone - go into Xcode - run the project and open back up the pokemon go game app on your phone.

It's been two days and I haven't gotten soft banned at all. Anytime I notice it teleport me back to my house whether it's a glitch or Xcode finishes that is what I do and never get banned.

**Comment by herocertified** [comment]
Known issue. Background music that was supposed to keep app running was not working. Should be fixed in 1.1.2.

See #121

**Comment by iam4x** [comment]
Should be fixed into last version v1.2.0
