### ISSUE TITLE
No debug  options

### ISSUE THREAD

**Issue by udaiveerS** [iam4x/pokemongo-webspoof#199]
I have the app build and downloaded. Phone is connected. I enabled terminal.app/script editor/pokemongo-webspoof in accesibility, but when I go to debug it gives me no options.

![image](https://cloud.githubusercontent.com/assets/12993700/17077246/d1c5996e-507d-11e6-9aca-aa8d8102fbba.png)

**Comment by wdg** [comment]
- Have you attached it to your ios device?
- Is the good iOS device selected (your iOS device name)
- Is the session running (the blank app)

Is this correct? then please make a full Xcode window screenshot, now we can't see what is going on.

**Comment by udaiveerS** [comment]
Actually think it might be my environment setup. If I build my own project in Objective-C options show up.
