### ISSUE TITLE
Getting App ID identifier error when trying to run the xcode

### ISSUE THREAD

**Issue by nejikon** [iam4x/pokemongo-webspoof#2]
it says: "An App ID with Identifier 'com.iam4x.pokemon-webspoof' is not available. Please enter a different string."

What do I do?

**Comment by stefan-o** [comment]
Just randomly rename it to something else or append it with random characters...

**Comment by nejikon** [comment]
Okay that fixed it

However, my PokemonLocation.GPX file is red and in inaccessible from the debug menu, how can I make it functioning? 

![image](https://cloud.githubusercontent.com/assets/20485293/16892632/ad46430e-4ae7-11e6-89c7-a18f29c735f5.png)

**Comment by nejikon** [comment]
nvm i made my own, this is fixed, it is working now thanks!

**Comment by pReya** [comment]
@nejikon How did you fix this? I do have the same problem. The gpx File is red and I can't find it in the Location dropdown. Also I can't find in in the filesystem to import it manually.

**Comment by iam4x** [comment]
@pReya @nejikon Track the gpx missing issue here #4 

(fix is incoming)
