### ISSUE TITLE
XCode wont let me set location via debug tab

### ISSUE THREAD

**Issue by dannyhtek** [iam4x/pokemongo-webspoof#20]
I feel like an idiot, but am I the only one who has not been able to set the pokemonLocation via the debug tab? I have followed the steps, but it's just not showing up. The 'Auto update xcode location' has been set.

**Comment by iam4x** [comment]
Move a little in the desktop app it will write the `pokemonLocation.gpx` file to disk and allow you to pick it in the debug menu 👍 

Related to #4
