### ISSUE TITLE
pokemonLocation.gpx is invalid

### ISSUE THREAD

**Issue by derbino** [iam4x/pokemongo-webspoof#200]
Hello,
when i start the Location simulation, i get the Error: 

Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid.

Does somebody has any idea?

**Comment by iX315** [comment]
move the map cursor and try again...

**Comment by chris284** [comment]
Same issue here. Xcode 8 beta 3, iOS 10.

**Comment by derbino** [comment]
@iX315 the map does not open....

**Comment by iX315** [comment]
@derbino which app version and OS X system did you use?

**Comment by derbino** [comment]
10.11.6 (15G31) / osx 9, no beta
all updated

**Comment by iX315** [comment]
@derbino did you use [THIS](https://github.com/iam4x/pokemongo-webspoof/releases/download/v1.1.1/pokemongo-webspoof-v111.app.tar.gz) ?

**Comment by derbino** [comment]
Thank you!

**Comment by chris284** [comment]
@iX315. No I cloned it. I'll try that.

**Comment by chris284** [comment]
Got it working with the download. Immediately soft banned. Tried a new account, and soft banned again. Damn!
