### ISSUE TITLE
Not moving on iPhone, No errors anywhere.

### ISSUE THREAD

**Issue by Spatch1** [iam4x/pokemongo-webspoof#204]
I followed all the instructions and get no errors, I move around on the map but Nothing moves on my iPhone. Any idea how to help me? 

Thank you.

**Comment by derpsoul** [comment]
Try going debug and chose pokemon map as location. Even though it might already be checked, check it again.

**Comment by Resnaad** [comment]
I'm experiencing the same thing.
Open Locationspoof software.
Going to Xcode, changing bundle name, building on iPhone. Simulator pops up white saying "You're good to go"
Going go the locator, putting on "Auto update Xcode location"
error xcode 2
going to Xcode, debug, location pokemon check.
Back to spoof locator, its working, no errors, but phone GPS doesnt move, not in pokemon, not in maps.
