### ISSUE TITLE
Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by p3ps111** [iam4x/pokemongo-webspoof#205]
This keeps happening every few minutes. I am on ios 10 beta

**Comment by herocertified** [comment]
Known issue. Supposed to be fixed in 1.1.2
See #178

**Comment by cbarrue** [comment]
Yes, happens quite often. Lets wait for 1.1.2 thanks.

**Comment by thomasdetrein24** [comment]
I'm getting the issue after every 30 seconds or so.. Really dunno how to resolve it. Hope it will get fixed soon.

**Comment by iam4x** [comment]
Should be fixed in last release https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.0
