### ISSUE TITLE
Search bar not working - Doesn't show autocomplete results any longer

### ISSUE THREAD

**Issue by Lynxdragon** [iam4x/pokemongo-webspoof#209]
![nosearch](https://cloud.githubusercontent.com/assets/1634678/17080672/a61656fa-518b-11e6-813b-36ff6fc16d32.png)
When typing into the search bar, no results are shown. Worked fine 12 hours ago, Also noticed on the Algolia Places website it does the same thing?

**Comment by 1YKM** [comment]
I feel as if the Algolia Places that's implemented isn't all that great. It might be better if you could just enter the lat and long or use google maps search instead.

**Comment by Lynxdragon** [comment]
I've managed to get the offical algolia places website to work, previously it did nothing. still does nothing in the app. Possibly a request limit?

**Comment by KoetseJ** [comment]
Could Algolia Places be changed for Google Directions? Because a lot of streets are no in Algolia Places, also you cant enter names of land sights or Lat and Long.

**Comment by Lynxdragon** [comment]
Decided its going to work again...

**Comment by iam4x** [comment]
Track issue here #64
