### ISSUE TITLE
App screen is white

### ISSUE THREAD

**Issue by chrisabrams** [iam4x/pokemongo-webspoof#21]
I followed the directions, but when opening the app on an iOS device, the screen is just an empty white background.

**Comment by clockw1ze** [comment]
How did you fix this? I also get a white screen on my iPhone.

**Comment by chrisabrams** [comment]
That's what it's supposed to do. There's nothing to do on the phone. It's all in the desktop app.

**Comment by clockw1ze** [comment]
But what do i do when my screen is white on the iphone? I dont see any desktop app running on my Mac Pro.

**Comment by clockw1ze** [comment]
I might be stupid, but where do i find the desktop app in the zip? 
Totally new to this stuff.

**Comment by jessedobbelaere** [comment]
Download the last release (link is under the image in the readme). Pick a location on the google maps viewer. 
Then you install the app on iphone, run it, it's a white app that doesnt do anything. Then you go to Debug > Simulate location and set your phone to the pokemonLocation. Then you just open pokemon go (leave the white app running in the background) and play

**Comment by chrisabrams** [comment]
When you download the zip (this is from the README): https://github.com/iam4x/pokemongo-webspoof/releases/download/v1.0.2/pokemongo-webspoof.app.tar.gz

The desktop app is the only thing in there. You double click it, and it will open both the desktop app as well as XCode. You use XCode to build the iPhone app (which is blank, that's fine).

**Comment by clockw1ze** [comment]
Ahh thats how it works. One more thing. When i go to debug simulate location i dont see "pokemonLocation" in the list. It's also red in the left under the webspoof branch

**Comment by chrisabrams** [comment]
Move yourself in the desktop app at least one step first. Then it shows up.

**Comment by clockw1ze** [comment]
Hmm doesn't seem to work, i get red windows with errors in the desktop app.

**Comment by iam4x** [comment]
@clockw1ze https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874

**Comment by clockw1ze** [comment]
I got it working but...
Do I have to repeat the steps everytime I want to use the spoof app?

I launch PoGo in iphone, open the spoof app on mac, change the build name thingy in xcode, build, run on iphone, move on map, debug->pokemonlocation, then it works.

Do i have to do all these steps everytime?
