### ISSUE TITLE
canOpenUrl: Failed for URL

### ISSUE THREAD

**Issue by MarkWaldron** [iam4x/pokemongo-webspoof#211]
Xcode Version: 7.3.1
OS X Version: 10.11.5
iOS version: 9.3.2
PokemonGo Webspoof Version: 1.1.1

Launching app on iPhone. Launching Webspoof App. Building app and launching. Whenever I click 'Launch Pokemon Go' I get the following error message:

`Pokemon WebSpoof[15907:4962357] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"`

**Comment by mmplisskin** [comment]
@MarkWaldron Did you happen to find a solution? I am having the same issue.

**Comment by bduebel** [comment]
Same issue here.

**Comment by shendykurnia** [comment]
As of today, after there is Pokemon Go new update, it's com.googleusercontent.apps.848232511240-dmrj3gba506c9svge2p9gq35p1fg654p
Need to update pokemongo-webspoof.app/Contents/Resources/app/xcode-project/pokemon-webspoof/Info.plist and 
pokemongo-webspoof.app/Contents/Resources/app/xcode-project/pokemon-webspoof/ViewController.m

**Comment by shendykurnia** [comment]
@iam4x
