### ISSUE TITLE
Add pokemon map support!!

### ISSUE THREAD

**Issue by khuangia** [iam4x/pokemongo-webspoof#212]
please see github: Pokemon-Go-Map or PokemonVision.com, it could show up the nearby pokemon and what it exactly is, if pokemongo-webspoof can do this, that will be so so so so sos so so so COOL!

**Comment by markadrake** [comment]
https://pokevision.com/

Second this - it would be great to filter by specific Pokemon you are looking for and integrate a click to travel on the map in electron.

**Comment by jasmow** [comment]
The app does have a community built pokemon tracker integrated. However from the looks of things, it doesn't use sniffed data, so real time pokemon spawns aren't integrated. The app also seems to be largely populated by sightings of pokemon in Europe.

**Comment by ataetgi** [comment]
yea it would be great if you can mix with pokemon-go-map

**Comment by Mardaneus86** [comment]
I have hacked a Pokevision overlay in my own version of this. Doesn't work good enough yet, but I am unsure if it's related to the current Pokevision instability. Could make a PR with my current adjustments, although it isn't the best code (currently learning React and Electron) if you guys are interested.
<img width="1002" alt="pokevision" src="https://cloud.githubusercontent.com/assets/7780108/17085063/b7a69afc-51c6-11e6-9c7a-f091eb2bcb3d.png">

**Comment by TCB13** [comment]
Since there are lots of projects to find and show Pokemons on maps it would be nice you can make LocationSpoof listen on a port (or fetch a specific URL) for Pokemon locations... (preferably with a UI option to turn on/off change URL).

**Comment by iam4x** [comment]
See original issue here: #54
