### ISSUE TITLE
System Event got an error can't get menu item Pokemon location

### ISSUE THREAD

**Issue by radjivC** [iam4x/pokemongo-webspoof#216]
![screen shot 2016-07-24 at 2 53 13 pm](https://cloud.githubusercontent.com/assets/5714138/17081934/66bc16ca-51ae-11e6-88c2-e5825e2e14bc.png)

I got this error after launching it. Any ideas?

**Comment by TCB13** [comment]
Check #185 .

**Comment by iam4x** [comment]
Duplicated
