### ISSUE TITLE
Help wanted! Phone GPS location doesnt change though everything on mac works

### ISSUE THREAD

**Issue by Resnaad** [iam4x/pokemongo-webspoof#219]
My going through:
Open Pokemon-webspoof.
Xcode: changing bundle name, then building on iPhone. Simulator pops up white saying "You're good to go"
Going go the locator, putting on "Auto update Xcode location"
error xcode 2
going to Xcode -> Debug -> pokemonlocation check
Back to spoof locator, its working, no errors!
BUT phone GPS location doesnt change - not in maps, not in pokemon.

Please help

**Comment by Spatch1** [comment]
Try this before you change the build name in xcode

Xcode > Product > Destination > 'YOUR PHONE NAME'

**Comment by Resnaad** [comment]
Wow im a moron! Thanks mate!
