### ISSUE TITLE
Homebrew Formula?

### ISSUE THREAD

**Issue by migueloller** [iam4x/pokemongo-webspoof#22]

**Comment by iam4x** [comment]
Feel free to open a PR for it, I have no knowledge to write homebrew formulas.

**Comment by elfenars** [comment]
Doesn't make sense, since you still need to clone the project and do all the setup by yourself.
The whole idea of homebrew is to have self-contained apps.

**Comment by iam4x** [comment]
Alright I'll just close this 👍
