### ISSUE TITLE
WebSpoof App Crashes often

### ISSUE THREAD

**Issue by Mojo90** [iam4x/pokemongo-webspoof#222]
Sometimes when a pokemon shows up the app crashes or currently it definetely crashes if I catch a Pokemon --> will be set back to my real location and have to start the app via xcode again. sometimes it crashes random.
Is this a known bug and is there currently any workaround available? (ios 10 beta3 on iphone 6 plus)

**Comment by KoetseJ** [comment]
Can you check if the Xcode debugger mentions something like: "Terminated due to memory issue"?

**Comment by Gernatch** [comment]
Other posts state this will be fixed in 1.1.2. We just have to wait until then.

**Comment by Mojo90** [comment]
okay but funnily ennough it did not happen again
