### ISSUE TITLE
pokemongo-webspoof app stops running every 5mins

### ISSUE THREAD

**Issue by qitang** [iam4x/pokemongo-webspoof#223]
Hi, the pokemongo-webspoof app stops running every 5mins so that I am always sent back to my original place. I also see some warning like this.

The provisioning profile "iOS Team Provisioning Profile: com.iam4x.pokemon-webspoofXXX" is expiring soon

Wondering it is because of this. Any help would be appreciated. Thanks!

**Comment by TCB13** [comment]
Have you changed the bundle identifier to something unique not the default?

**Comment by qitang** [comment]
@TCB13  I think so. If the bundle identifier is not unique, you won't even be able to launch the app I think.

**Comment by TCB13** [comment]
@qitang if so, Xcode should automatically generate provisioning profiles which expire in about a week. Maybe you can go into Xcode preferences > Accounts and remove your Apple ID using the the (-) signal at the bottom. Then close everything, run the App again, login with your Apple ID when required and new profiles should be there...

**Comment by iam4x** [comment]
Should be fixed with last release https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.0
