### ISSUE TITLE
updated to v1.1.1 : can't be launched anymore

### ISSUE THREAD

**Issue by ilikesomething** [iam4x/pokemongo-webspoof#225]
I was on the version 1.1.0 and everything worked fine.

I updated to v1.1.1 and when i launch it on my MAC, the icon just hang on the dock for a few second and then close. (i don't see any app and XCODE doesn't launch like it did at the same time on the previous version)

By the way i authorise installs from all sources

I can't stay on v1.1.0 cause i need to enter negative coordinates and it doesn't work..

**Comment by ao95** [comment]
Had the same issue, solved it by cloning the repo and running it "dev mode" but I guess that's not possible for everyone to do..

**Comment by iam4x** [comment]
Be sure to have only one .app on your Mac.
