### ISSUE TITLE
Please fix this new update ASAP

### ISSUE THREAD

**Issue by Jimmymork** [iam4x/pokemongo-webspoof#226]
Can't drag map (yes, I did click the unlock map dragging button which is not working apparently), cannot jump to any location by typing it in the search bar. Can't even use the older versions for some reason, the app is broken. Someone please fix this

**Comment by Gernatch** [comment]
I'm sure they're working on it. This has all been reported. I'm also anxious, but as a dev myself, I can say this stuff can take a while. I'm shocked they've completed this much in such a short time...

My issue is the memory crash. I keep teleporting back to my starting point. I'm afraid of getting banned because of this.

**Comment by Jimmymork** [comment]
Happens to me as well, if you're lucky enoguh it wont happen while you're capturing Pokemon, battling a gym, ect. since you can quickly double tap the home button and close the app to not get banned. Also found a temp "solution" - latitudes can be used for locations, although dots cannot be entered -_-

Edit: The location function is region locked, and America is not coutned as one but as South, Central and North America... trying to change location to another region will result in an error - use latitudes to change region then go precise with the search bar.

**Comment by sovanbu** [comment]
I could never get the map to pop up in Xcode. I compiled the code, installed the spoof on my phone, but could never get a map to open in Xcode, and when I went up to do the location selection it gave me an error. So does this still work or was I doing it wrong?

**Comment by Jimmymork** [comment]
Try writing down the Longitude and Latitude instead, works for me
