### ISSUE TITLE
Soft banned

### ISSUE THREAD

**Issue by Guizmo12** [iam4x/pokemongo-webspoof#227]
Hey guys, 

BTW, really awesome app. You guys are making this look easy ! 

Just want to know what is the best way not to be soft banned. I'm living in Canada, but if I want to walk in Santa Monica for few hours ?

What I have tryied:
1. Open PokeGo with the shortcut in Webspoof and moving while PokeGo opens
2. selecting in the Debug poke webspoof before doing enything
3. Staying in my region and wishing for a new transport speed; Planes 400km/h

Thoughts ?

**Comment by Mardaneus86** [comment]
Probably by not travelling faster than you would be able to in real life. For example; traveling from Europe to USA in anything over 8 hours or so is realistic (depending on east or west coast and where in Europe). Make your moves as realistic as possible.

Make sure you don't use the app for that period of time beforehand. Also don't open Pokemon Go before you travelled to the location. Try not to teleport while the app is open, only use the other transport modes if you have the game active.

**Comment by iam4x** [comment]
There's a lot of issues on this subject, search through issues.
