### ISSUE TITLE
Option doesn't exist: Debug -> Simulate Location -> pokemonLocation

### ISSUE THREAD

**Issue by chrisabrams** [iam4x/pokemongo-webspoof#23]

**Comment by iam4x** [comment]
Check "Auto updated Xcode location" and move a little on the map, it will write to file `pokemonLocation.gpx` and then the option will appear 👍 

It's a known issue I'm working on a fix, will release new version tomorrow I hope.

#4

**Comment by chrisabrams** [comment]
Moving a few steps resolved the issue. Thx!
