### ISSUE TITLE
Cant catch any pokemon and pokestops

### ISSUE THREAD

**Issue by angrhvito** [iam4x/pokemongo-webspoof#230]
Hello, did anybody experiencing the same issue? I cant catch any pokemon and cant get any item in pokestop when using pokemongo-webspoof. It's like whenever I tried to catch pokemon, the pokemon always run. and when I swipe the pokestops, the item in pokestops wont come out. Any clue? thanks

**Comment by Guizmo12** [comment]
You have been soft banned. wait few hours. You need to travel like a real human. Try not to teleport everywhere.

**Comment by iam4x** [comment]
See README for note about soft-ban
