### ISSUE TITLE
Quick Start!

### ISSUE THREAD

**Issue by pollo881** [iam4x/pokemongo-webspoof#233]
First of all good job to iam4x and all the contributors..really nice!
I state that the only experience i have in matter of programming environmets is Max/MSP so i don t know much about app oriented ones as xcode.
I've followed the "how-to-run" procedure and after couple of trials it worked quite smoothly for a few times...once freezed my cell (force-restart and it was as new 👍 ). 
My question is if there's a way to save the xcode project once modified so i can start the procedure further ahead..ex: 
1. open the app on mac and modify gpx to avoid softban
2. connect phone and check the autoupdate xcode location
3. open PG through pokemongo-webspoof and simulate location
Thank you and keep going!

**Comment by iam4x** [comment]
Thank's, track original issue #75
