### ISSUE TITLE
 'openURL:' is deprecated

### ISSUE THREAD

**Issue by NicholasHord** [iam4x/pokemongo-webspoof#236]
/var/folders/lh/3vc5wdsx6t9454tp758gxbc8f0gdhq/T/tmp-53725h9UGCNazhyB9/xcode-project/pokemon-webspoof/ViewController.m:55:44: 'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead

<img width="1001" alt="screen shot 2016-07-25 at 3 19 15 pm" src="https://cloud.githubusercontent.com/assets/9059361/17115954/3b6dd33c-527b-11e6-9099-05110444d19b.png">

**Comment by NicholasHord** [comment]
Just posting the findings, i understand it is just a warning

**Comment by h4v1nfun** [comment]
@NicholasHord we are targeting iOS 8.0 atm and that deprecation warning is from iOS 10 as you can see in "First Deprecated in iOS 10." and "openURL:options:completionHandler:" isn't available in iOS 8 and 9.
But thanks for your findings 👍 

I'm going to close this.
