### ISSUE TITLE
Can't travel after first Spawn

### ISSUE THREAD

**Issue by renege** [iam4x/pokemongo-webspoof#239]
Hi, 
I spoofed my location via the App, that works, because I spawned there. But then I'm trying to move with the arrows, but that doesn't work. The same for "traveling" to other destinations. I keep standing in the same spot. What am I missing?

**Comment by Gernatch** [comment]
Same for me...

**Comment by Gernatch** [comment]
Dope... Had to check Auto update Xcode location again...

Also forgot to make it an approved app. It's been a long day.
