### ISSUE TITLE
Can't simulate location, fails with "pokemonLocation.gpx" is invalid.

### ISSUE THREAD

**Issue by ksulli10** [iam4x/pokemongo-webspoof#244]
I am running OS X 10.11 on a VM.  After I start the application I try to simulate the location and select the "pokemonLocation" gpx file, but it fails with the following error:

![untitled](https://cloud.githubusercontent.com/assets/20649230/17126579/2de94ad6-52c4-11e6-805c-4bf662167476.jpg)

I read similar issue reports that mentioned adding pokemongo-webspoof to the Accessibility section, but it doesn't show up.  If I browse to the .app itself, it looks crossed out with a white circle no-smoking sign type thing.

Any ideas?

EDIT:  When I try to start the .app by clicking on it, it says "PowerPc applications are no longer supported."  Do I need an older OS version?  Google is telling me 10.6 or earlier.

**Comment by lanabug** [comment]
I was experiencing the exact same thing last night. What I did to fix is delete everything (besides xCode) and start from scratch with the newest version posted - pokemongo-webspoof.app.tar.gz (v1.2.0)
When I downloaded this one, I was graced with an actual .app file that opened on my desktop! From then on, follow the instructions.

**Comment by ksulli10** [comment]
@lanabug Are you running a VM and/or OS X 11?

**Comment by lanabug** [comment]
no I have a macbook pro. OS X 10.11.5

**Comment by ksulli10** [comment]
Thanks so much!  @lanabug   The problem was I was hitting "Clone and download" instead of clicking the ".tar.gz" link.  I clicked that and it works!
