### ISSUE TITLE
Invalid gps coordinates

### ISSUE THREAD

**Issue by snikch** [iam4x/pokemongo-webspoof#25]
I'm getting longitude of `-185.x` when it should be `175`. This results in a GPS error on the phone.

**Comment by iam4x** [comment]
@snikch Can you give me a location to go then how to reproduce? Thank's.

**Comment by snikch** [comment]
Looks like it's resolved in the autopilot branch - so not sure it's worth following up.

**Comment by iam4x** [comment]
Great 👍
