### ISSUE TITLE
Unable to Change Bundle Identifier

### ISSUE THREAD

**Issue by Mr10001** [iam4x/pokemongo-webspoof#252]
I'm clearly knew to iOS App Dev, I just purchased the 99$ subscription and am trying to follow the directions. However, I'm unable to change the bundle identifier as the Wiki indicates, as it's greyed out. I tried Google, but didn't find anything that seemed to work.

Any suggestions?

Thanks a million

**Comment by Mr10001** [comment]
I found a solution, where it said to remove the variable from the info.plist file. I removed the variable there and now I can edit the bundle identifier.

**Comment by waterwreath** [comment]
Which variable did you remove? I have the same issue. Also, do I need a developer id to compile and run??

**Comment by Mr10001** [comment]
The bundle identifier variable. =}

**Comment by waterwreath** [comment]
Do I need a developer ID? Don't really wanna pay $100 just to spoof gps....
