### ISSUE TITLE
Issue -1719 autoclick.apple.execution error

### ISSUE THREAD

**Issue by repteke** [iam4x/pokemongo-webspoof#257]
![skjermbilde 2016-07-26 kl 23 17 24](https://cloud.githubusercontent.com/assets/20666140/17155868/31ed253a-5387-11e6-8ee5-04bc526cc2d6.png)

So i´ve tried almost everything, re-installed - changed the privacy prefrerence. Does not work to change between locations or anything else. 

Hope you guys can help..

**Comment by gilmillasseau** [comment]
Security and Privacy > Privacy tab > Accessibility 
- Enable Pokemon Go
Done

**Comment by repteke** [comment]
![skjermbilde 2016-07-27 kl 06 57 18](https://cloud.githubusercontent.com/assets/20666140/17164322/6b68575e-53c7-11e6-82c6-e4b89075eda9.png)

![skjermbilde 2016-07-27 kl 07 01 37](https://cloud.githubusercontent.com/assets/20666140/17164399/099a6020-53c8-11e6-864b-240950c9a133.png)



Doesn´t do the trick for me, this is the third time i´ve deleted the app > re-dl it > re-install >privacy accessibility > run app > followed all the steps > and when i try to transport or move around on the map i get the message in the 1st post..

**Comment by ninovandenheuvel** [comment]
Same for me. Keep getting that error.

**Comment by repteke** [comment]
https://www.youtube.com/watch?v=4BmtrlcypZg

I uninstalled everyting from the  ~/Library that was connected to Pokemon webspoof - then i followed everything the dude did on his screen. It´s in german which i don´t speak - but i still got it working. 

Good luck!

**Comment by StefanMeGit** [comment]
What did you uninstalled in the Library? Cant find there anything...

**Comment by repteke** [comment]
I had installed the app more than one time, so when i re-installed it the last time i deleted everything connected to the pokemon webspoof. 

Then  i followed the steps in the YouTube vid i posted.
