### ISSUE TITLE
I cant seem to get it working on macOS Sierra and iOS 10 w/xCode beta, keeps giving me a 'Error Autoclick xCode - Code 2" error

### ISSUE THREAD

**Issue by pri8771** [iam4x/pokemongo-webspoof#258]

**Comment by gilmillasseau** [comment]
Security and Privacy > Privacy tab > Accessibility 
- Enable Pokemon Go
Done

**Comment by nickg819** [comment]
GitHub needs an "auto-respond" option for certain keywords like this post. I can't imagine how many posts the leads on this project are having to remove related to specific requests that have been answered hundreds of times.
