### ISSUE TITLE
Set up for development

### ISSUE THREAD

**Issue by neobugbounty** [iam4x/pokemongo-webspoof#26]
Hello,

I would like to fix some bugs, and add new features, as I am addicted to the game. :)

Can you publish a guide on how to quickly set it up for development? I have never developed anything for iOS, so I have no clue how to begin with.

Thank You

**Comment by iam4x** [comment]
I'll add some notes on the README.md, you will notice that the app is written in JavaScript on top of Electron + React + Mobx 👍
