### ISSUE TITLE
Unable to add pokemongo-webspoof to Privacy Section?

### ISSUE THREAD

**Issue by Mr10001** [iam4x/pokemongo-webspoof#269]
Unable to add pokemongo-webspoof to the privacy section? I can't add the xcode project file and I tried searching for a .app file, but found nothing.

What am I missing?

**Comment by ksulli10** [comment]
Make sure you are downloading the "pokemongo-webspoof-1.2.0.tar.gz" file, and not clicking "Clone and download."

After you gunzip and untar the file that gets downloaded, the only thing in the folder should be an .app file.

**Comment by Mr10001** [comment]
Thank you ksulli10. However, I actually just found it after looking in the project within xcode. It was under: pokemon-webspoof > Products > Pokemon Webspoof.app

The directory was listed on the right side as being under:

Users/<YOURUSERNAME>/Library/Developer/Xcode/DerivedData/pokemon-webspoof-efvpbovblhrvsydtlnvxnoqhllwz/Build/Products/Debug-iphoneos/Pokemon WebSpoof.app

I simply navigated to this directory and then dragged and dropped the .app file to the privacy section.

**Comment by ksulli10** [comment]
I did that as well, and I don't believe it's going to work.  You're gonna get an invalid GPX file error message.  Also the GUI never opened for you, did it?  And it has a white cross-out image on it?

**Comment by Mr10001** [comment]
I was receiving that until I updated the "pokemonLocation.gpx" by looking for an example online... I'm not sure if it's correct or not, but it looks like:

<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0">
    <name>WPS</name>
    <wpt lat="XX.XXXXX" lon="-XX.XXXXXX">
    </wpt>
</gpx>

The app does not open on my Mac, but does open on my iOS device. I'm still stuck on step 18 though. 
"Select the "Auto update Xcode location" in top corner of the Pokemon Go Webspoof app when everything is running"

**Comment by ksulli10** [comment]
Yeah, haha I'm telling you.  Completely remove all of that, and start over without using "Clone and download."  Click the 1.2.0 tar.gz file.  The only thing in the folder after extracting should be a .app file, and when you click it the GUI opens before everything else.  If that's not happening, you downloaded the wrong thing.

**Comment by Mr10001** [comment]
Ah, I see it now. Thank you!
