### ISSUE TITLE
Pokevison code, add?

### ISSUE THREAD

**Issue by Boreland125** [iam4x/pokemongo-webspoof#270]
How do I add the poke vision code to the location spoof?

**Comment by FreshDonut** [comment]
It hasn't been released on the main branch yet. You can mess with it from within the [pokevision](https://github.com/iam4x/pokemongo-webspoof/tree/pokevision) branch. Note: It's currently in development, and it may contain bugs and other issues.

**Comment by lukesnowden** [comment]
https://skiplagged.com/pokemon uses the same map, easier to navigate to.

**Comment by iam4x** [comment]
Need a better map, will happen at sometimes it planned.
