### ISSUE TITLE
Stay on pokemonLocation

### ISSUE THREAD

**Issue by jasoneo016** [iam4x/pokemongo-webspoof#274]
Whenever I run the program, I would go somewhere, and then xCode would randomly lose my pokemonLocation and go back to my actual current location. This defeats the purpose of this tool. I would never be able to actually utilize any pokestops nor catch any pokemon since the invisible bubble has to catch up to me and gives me a soft ban...any suggestions would be helpful this is extremely frustrating.

**Comment by kingofbklyn** [comment]
Ah, this happens to me as well.

**Comment by cheeseonhead** [comment]
When you notice that happening, do not interact with anything in the current location and immediately close the app. Then rebuild from xcode, while launching pokemon go move around on the mac app to make sure it sends out the spoofed location. You will still be able to interact

**Comment by iam4x** [comment]
Fixed into latest version #384
