### ISSUE TITLE
location spoofed but nothing  works when i'm there.

### ISSUE THREAD

**Issue by caranicas** [iam4x/pokemongo-webspoof#276]
I ran into this issue earlier today, but then I tried again and I got it working but now it is broken again.

I can spoof my location just fine and move around but any pokestop i try to interact with will just spin and never give me any goodies. I can start an encounter with pokemon but they immediately escape the ball and then run away. 

any advice would be great.

**Comment by joshpalan** [comment]
This is a soft ban. Don't move too far too quickly.

**Comment by caranicas** [comment]
oh ok, that makes sense. But then how do I start where I want to and not exactly where I am first and then jump to where I want to be?

**Comment by zrherda** [comment]
I am in the same boat. How can I spoof my location first and then be fine where I am at. It always loads my current no matter what then jumps. Causing the soft ban.

**Comment by caranicas** [comment]
The instructions are bad. Don't start PokemonGo first.  In Xcode run the spoof app. Then in the electron app tell it to auto update and set your desired location.  Then do debug set location to pokemap location. Then on your iPhone use the spoof app to open Pokemon go.  Then you load immediately to where you want.  If you want to confirm you can open a maps app first and you will see the spoofed location.

**Comment by zrherda** [comment]
That seems to work. Does anyone know the cool down between jumps? For example, spoofed to Cali from AZ to test the instructions and it worked great. Shut it down and restarted and jumped to NY and soft ban.

**Comment by joshpalan** [comment]
I'm almost positive they have their own formula that calculates distance
traveled within time passed since last request. What the distance to time
ratio is I still have yet to figure out.
