### ISSUE TITLE
[Suggestion] Add Latitude and Longitude

### ISSUE THREAD

**Issue by yidongw** [iam4x/pokemongo-webspoof#281]
Awesome work.

Can you please add a function that I can input the destination by Latitude and Longitude?

Thx

**Comment by Mardaneus86** [comment]
You already can, however there are certain drawbacks with the current implementation as it is a way to enter coordinates, but they also get updated by location changes.

See #190 for a workaround.

**Comment by yidongw** [comment]
I see what are you suggested, but I have problems with copy paste number into these two columns

**Comment by derpsoul** [comment]
it's pretty much useless as it doesn't take in negative or decimals when inputting, if you do it will default to NaN and have no way of changing it but to restart the app

https://github.com/iam4x/pokemongo-webspoof/issues/261

**Comment by iam4x** [comment]
This a bug already reported https://github.com/iam4x/pokemongo-webspoof/issues/62#issuecomment-234351434
