### ISSUE TITLE
How do i get back to "normal" use of Pokemon Go?

### ISSUE THREAD

**Issue by absolut-times** [iam4x/pokemongo-webspoof#282]
So i tried the webspoof with my iPhone 6s and MacBook Pro (Mid 2010, OS X El Capitan) and it worked very nicely. Great work!

But now i want to go back and use the app the _normal_ way again, but it wont recognize my real location anymore. Everytime i start the app without the webspoof and xCode running, i'm still stuck at the last location i visited via spoof.

Any ideas?

Thx,
Times

**Comment by uae980** [comment]
on Xcode go to Debug ---> simulate location ----> Don't simulate location

**Comment by onmyway133** [comment]
@absolut-times yeah, interesting, I get this behaviour as well. Sometimes the app recognizes my current location, sometimes my last websproof location

**Comment by Simbe90** [comment]
Restarting the phone works fine for me.

**Comment by absolut-times** [comment]
Restarting worked, thanks.
