### ISSUE TITLE
Jumping outside the US

### ISSUE THREAD

**Issue by pantalones-de-cheese** [iam4x/pokemongo-webspoof#284]
I know in older versions you could just jump to locations. Now you can only go to locations that are reachable by walking or driving. Is it bad to want to jump to france?

**Comment by FreshDonut** [comment]
Realistically if you want to go to France in in real-life it takes 16 hours flying, don't play the game for 16 hours. Then next time you open it you can teleport prior to running it.

**Comment by alexpearce92** [comment]
You can also turn off Pokemon Go (force quit), jump to France in webspoof, and validate the GPS change in Google Maps on your phone. Reopen Pokemon Go and you will be in France without a soft ban

**Comment by kebabortega** [comment]
@alexpearce92 i still got a soft ban :(

**Comment by alexpearce92** [comment]
I've found that you have to wait several hours between jumping locations at great distances. The dev's must have built in some logic around switching locations too quickly. Usually what I'll do is not check PG in the morning when I wake up and instead spoof to the location I want to be at. If I turn on PG to my current location and then quickly change it to the other side of the world, I will get soft banned

**Comment by iam4x** [comment]
#326
