### ISSUE TITLE
GPS Locked after using this?

### ISSUE THREAD

**Issue by Olorin92** [iam4x/pokemongo-webspoof#29]
I noticed that after using this app, when trying to go back to just my iPhone and play normally, I'm stuck in the previous location. Restarting my phone seems to fix it up, but has anyone else had this problem?

Also, I know it's a hard question to answer, but how likely are you to be soft banned if moving around at the lowest speed?

Cheers,

Alex

**Comment by Svena69** [comment]
^ I've experienced this problem too. It seems like they put you on soft ban when you 'teleport' from 1 place to another in a too far radius. Let's say you teleport from London to New York, they'll notice and you'll get soft banned. If you stay in your own city you shouldn't get soft banned ever.

It also seems like they put you back in a certain location every 5-10 minutes. I'm not sure why but I think that's the time they 'force' update your location. 

& The answer to your question: 

> Also, I know it's a hard question to answer, but how likely are you to be soft banned if moving around at the lowest speed?

^ Very unlikely.

**Comment by Olorin92** [comment]
Well I just went around Melbourne now, and no ban yet. Does it sometimes take a while for a soft ban to kick in? Or is it usually instant? 

Also, I noticed I was frequently getting up to around 22km/h when walking around in the app. Do you think this is getting close to being dangerous in terms of being caught?

**Comment by iam4x** [comment]
@Olorin92 

* Softban are instants, it happens when you jump like 10km in a second but don't stay long (it happens once or twice to me, but lasted for 5-15minutes)
* Nope, it's only on big locations jump 👍

**Comment by iam4x** [comment]
And if you are stuck a certain location, just reboot your iOS device.
