### ISSUE TITLE
Not allowing me to simulate "pokemonLocation"

### ISSUE THREAD

**Issue by RSGC-LOWRY-J** [iam4x/pokemongo-webspoof#298]
I've had it working once, but now it greys out any option to simulate location.

<img width="559" alt="screen shot 2016-07-30 at 1 47 46 pm" src="https://cloud.githubusercontent.com/assets/14804223/17272127/a716e88c-565c-11e6-8504-f2f15da2448d.png">

**Comment by epilande** [comment]
@RSGC-LOWRY-J build `pokemon-webspoof` app & keep it running on your phone

**Comment by RSGC-LOWRY-J** [comment]
@epilande it is running, should something other than the pokemon-webspoof desktop app be running?

**Comment by Cory-Bennett** [comment]
Try moving a bit using the arrow keys on the pokemon-webspoof

**Comment by RSGC-LOWRY-J** [comment]
Turns out I had to run the app, and pokemon go, close them again, and then run it via Xcode to make it work.
