### ISSUE TITLE
Location issues

### ISSUE THREAD

**Issue by stefan-o** [iam4x/pokemongo-webspoof#3]
Everything is working well but it seems after a while, it randomly will reset to your _actual_ location even sometimes catching pokemon or interacting with certain menu's it will reset to _actual_ location.

I think just need to investigate further to avoid being detected using this, e.g. 10-15km+ from actual location.

Also if you're going 20km+ from your actual location, all pokemon tend to escape and/or pokestops don't work.

**Comment by stefan-o** [comment]
Just tested the app by using my actual location - now all pokemon run away from me after the first pokeball hit.

**Comment by stefan-o** [comment]
Might add as well I think it works better with Wifi off.

**Comment by iam4x** [comment]
@stefan-o Do you think Pokemon Go checks your internet connection location as well? I had this once where my player jumped back to home after a pokemon catch.

All pokémons are still running away?

**Comment by stefan-o** [comment]
@iam4x, I'm thinking they have server logic for when your trainer jumps to another location 5-10km+ rapidly that then the server won't let you function in that area or any areas for a while. Just an assumption at this stage but have replicated this three times already.

I think the wifi enabled could lead to another issue as wifi increases GPS accuracy and it will update coordinates itself, so running the app with wifi isn't recommended.

**Comment by ChaseGiunta** [comment]
If all the pokemon are running away after you've jumped locations, that means you've been soft banned.

**Comment by ataetgi** [comment]
i have same issue sometimes resets my location to actual but if i check on google maps application i see I'm at fake location. idk why this happens

**Comment by madvas** [comment]
When I'm using this, no pokemon seems to appear to me, even if I'm standing right on green leaves. But, I can go to pokestops to collect items. Or even egg hatching distance counts. Does that mean some kind of ban? 

PS: You've done awesome job with this anyway, thanks ;)

**Comment by iam4x** [comment]
@madvas Thanks :)

 I don't think, it's just server issues it's really buggy right now. Happens to me also.

**Comment by madvas** [comment]
@iam4x You're right, I already managed to catch some, thanks again! ;)

**Comment by ffr** [comment]
When I'm using this, I jumped, but no pokestops around, anywhere...

**Comment by iam4x** [comment]
@ffr This is a pokémon go server issues, kill and restart app.

**Comment by nickgassmann** [comment]
@iam4x I just popped open google maps and have the same issue @ataetgi saw a few days ago. Need to know how to "turn off" so that if we are away from our computers we can use location apps as normal.

**Comment by iam4x** [comment]
@nickgassmann check #45 for more informations on how to solve that 👍

**Comment by iam4x** [comment]
Fixed into v1.1.0 https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.0
