### ISSUE TITLE
Starting in a certain location?

### ISSUE THREAD

**Issue by Lumerias** [iam4x/pokemongo-webspoof#30]
Is there a way to start in a different location? Meaning, can I start PokemonGo after I have started the webspoof app and I'll automatically appear wherever I have the map? I tried doing this and it had my real location and then when I moved the arrows it updated my location resulting in a soft ban.

**Comment by iam4x** [comment]
1. Start pokemongo-webspoof.app but **dont start pokémon go on your device yet**
2. Click on "Enable auto Xcode location update"
3. Go to your place (don't worry about the error `cannot click on menu item...`)
4. Connect your iOS device, build the app on it
5. Move once in the Mac app (it will update `pokemonLocation.gpx` with new coordinates)
6. Make sure pokemonLocation is selected in Xcode (Debug -> Simulate Location -> pokemonLocation)
7. Start pokémon go and play at the place!
