### ISSUE TITLE
Click map and autopilot to the dropped pin

### ISSUE THREAD

**Issue by jnrepo** [iam4x/pokemongo-webspoof#301]
I find it difficult to find the address of the place I'd like to go to every time. It'd be nice if I could drop a pin on the map and autopilot there, rather than having to find the correct address and type it in.

I guess this is more of a feature request

**Comment by cheeseonhead** [comment]
It's already a thing tho

**Comment by jnrepo** [comment]
:O what! I see it! thank you!
