### ISSUE TITLE
after the new pokemon go update, the webspoof doesn't work anymore

### ISSUE THREAD

**Issue by annshbrna** [iam4x/pokemongo-webspoof#305]
I just updated the app, and when I clicked "launch pokemon go" it doesn't do anything.

**Comment by sbitswc** [comment]
similar issue, https://github.com/iam4x/pokemongo-webspoof/issues/302 
you probably need to fix the code to launch pokemon go correctly.

**Comment by goodasgood** [comment]
Hey - i got the same problem.
I did everything like the description says but at the end I wasn´t able to start the pokemon go app, because he don´t show the "launch pokemon go" button.

Please help - I´ve not so much clue with Xcode and all this stuff... thank youuuu

**Comment by winstein** [comment]
As long as the location was spoofed, you can still launch Pokemon Go independently and control from the mac.

**Comment by porkserver** [comment]
The Launch Pokemon Go link is just a convenience.  you can open the app after closing webspoof assuming keep running in background is ticked on.

**Comment by bullseye1975** [comment]
I am still having an issue where it compiles fine but nothing happens on the Mac (no map launches, etc).  Someone mentioned Security Privacy Accessability but clicking + to add doesn't work.  Not sure what file to add as they are all greyed out.

**Comment by iam4x** [comment]
Fixed in latest version.
