### ISSUE TITLE
New update for pokemon go - web spoof isn´t working - please help

### ISSUE THREAD

**Issue by goodasgood** [iam4x/pokemongo-webspoof#306]
Hey buddies,

i got a big problem with the pokemon go webspoof.
After the update i´m not able to play it anymore.
I press the button "launch pokemon go" and nothing happens.

Please help me. 
A description would be nice - because i don't have much experience with Xcode.

Thank youuuu
:)

**Comment by kebabortega** [comment]
it still work, i just launched the app manually in my home screen

**Comment by michael430** [comment]
kebabortega is right that the Pokemon WebSpoof app is still kind of working, just the "Launch Pokemon GO" does not work anymore with the newest Pokemon Go app. You need manually launch the app. 

However the GPS location seems very unstable compare before, the player location jumps often back to original location from where my iPhone is. I have to move with arrow key to update it.

Hopefully we can get a new update here soon and with PokeVision feature..:)

**Comment by michael430** [comment]
bittuahlawat has a solution for launch issue with new update, please check the threads [#302 Failed for url](https://github.com/iam4x/pokemongo-webspoof/issues/302)

**Comment by h4v1nfun** [comment]
Fixed in last commit
