### ISSUE TITLE
It keeps going back to the initial location

### ISSUE THREAD

**Issue by kebabortega** [iam4x/pokemongo-webspoof#307]
So I did the "build & run", -> select Auto Update Xcode Location then simulate the location (e.g. London) and open the phone.
In Iphone, the simulated location is ok, but the webspoof app in Mac did not change, it still locates me to the initial location and when I moved the arrow the location in the iphone directs me to the location in mac and I am banned afterthat.. What could be the problem?

**Comment by michael430** [comment]
Same Problem here. With newest Pokemon Go app updated, I believe the game is not launch via the WebSpoof app, which make the connection of GPS location not stable between game and WebSpoof app.

**Comment by nickg819** [comment]
Don't run the POGO app until you've got your location correct in your phone's map app. Make sure you can move around in the map app before launching pogo.

**Comment by kebabortega** [comment]
@nickg819 yup that is what i am doing now.. teleport first to the desired location, check in the google maps if you are really there... then run pokemon go
