### ISSUE TITLE
Failed to code sign Pokemon WebSpoof

### ISSUE THREAD

**Issue by Imaduffus** [iam4x/pokemongo-webspoof#312]
Dear all, thanks a lot first for this nice feature. While building on my iPhone I get following error message
Failed to code sign "Pokemon WebSpoof".
No non–expired provisioning profiles were found.

Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles.

I use the option to  fix issue - resolving code issues

followed by message
An App ID with Identifier 'com.iam4x.pokemon-webspoof' is not available. Please enter a different string.

Any ideas, what I can do about that

**Comment by pcmore** [comment]
You didn't rename the Bundle Indentifer.
Also you need to add your Apple ID in Xcode. (xCode -> Preferences -> Accounts)

**Comment by Imaduffus** [comment]
AWESOME THANKS ALOT *happy*
