### ISSUE TITLE
NEED TO UPDATE CFBundleURLScheme

### ISSUE THREAD

**Issue by matthewwicker** [iam4x/pokemongo-webspoof#313]
With update the BundleURLScheme has been changed. Because of this your application fails to open the pokemon go app. After you fix this if you could update me on how exactly you got the BundleURLScheme that would be awesome. 

Thanks!

**Comment by likfarmenhet** [comment]
You can start the app manually after running it in xcode, dont use the "launch pokemon go" button

**Comment by h4v1nfun** [comment]
Fixed in last commit
