### ISSUE TITLE
Pokemonlocation error after update

### ISSUE THREAD

**Issue by gingerrob1986** [iam4x/pokemongo-webspoof#314]
Hi, I think I sorted everything after the update, script built ok.
But now I have this issue when I select location in the debug area. 
Please help.
![screen shot 2016-07-31 at 16 16 53](https://cloud.githubusercontent.com/assets/20751397/17277811/746a7f3c-5744-11e6-86cf-9c31f212ebcc.png)

**Comment by amamut** [comment]
I have the same issue.

**Comment by giusti4** [comment]
same problem here

**Comment by gingerrob1986** [comment]
Are there any answers to this?

**Comment by nickg819** [comment]
Have you bothered searching all the tickets for the folks that already had this error? 

[#125](https://github.com/iam4x/pokemongo-webspoof/issues/125)
