### ISSUE TITLE
how to use this please

### ISSUE THREAD

**Issue by biiouii** [iam4x/pokemongo-webspoof#317]
how to use this please, make us a read me please

**Comment by XplicitKY** [comment]
It's at the front page... if you don't even bother reading that you should not use this

**Comment by XplicitKY** [comment]
It's on the front page

**Comment by yoh-m** [comment]
I think the rule "if you don't know how to use it, you should not be using it" has been applied while writing the doc, a few (simple) steps are missing. I don't want to be rude, but if you're not able to understand how it works with the doc as it is now... Maybe you should buy a bike ;) (or learn how to use tools like `npm`, that could work too)

**Comment by iam4x** [comment]
Read READM.md
