### ISSUE TITLE
Running for the second time

### ISSUE THREAD

**Issue by AidanMcArdle** [iam4x/pokemongo-webspoof#318]
This is not an issue, just a basic question about running the app. 

Followed the read-me to build and run via xcode just fine, the _first_ time.

However, to run the app for the second or subsequent times, I can't figure out how to do this without re-building a whole new instance of the app. If I try to re-open the old project in xcode, the map interface doesn't open. If I open it straight from my phone, neither xcode nor the map interface opens. If I open via the download, a new build begins.

What am I doing wrong here and how do I open all parts of my previous build simultaneously?

**Comment by iam4x** [comment]
Start by opening the mac app like on README 👍
