### ISSUE TITLE
ISSUE 107

### ISSUE THREAD

**Issue by litrairai** [iam4x/pokemongo-webspoof#322]
I'm confused. i download the app, it builds and runs properly. then i go onto my phone and attempt to click the big "launch pokemon GO" button in the middle and it does absolutely nothing

**Comment by Vaseltior** [comment]
There was an update yesterday of the PKMNG app, and they removed the URL scheme that permitted to launch the app from another app.

**Comment by litrairai** [comment]
so that means that the entire Xcode of pokemongo-webspoof is not usable?

**Comment by Vaseltior** [comment]
No, it works... The app is only there to update the GPS of the iPhone, as long as the WebspoofApp runs in background, it works.

**Comment by litrairai** [comment]
I'm still confused on how to get it to run in the background. even with the web spoof app open, then opening pokego, the app is the same

**Comment by litrairai** [comment]
never mind, works like fine. sorry for the confusion.

**Comment by iruy** [comment]
Check this [answer](https://github.com/iam4x/pokemongo-webspoof/issues/302#issuecomment-236410944) issue #302

**Comment by iam4x** [comment]
Fixed into last version
