### ISSUE TITLE
Being Reversed To My Main Location

### ISSUE THREAD

**Issue by paxuh** [iam4x/pokemongo-webspoof#323]
Hi,

I am being reversed to my actual location on device, even the xcodehas builded and webspoof shows I'm somewhere else This is not a good advantage especially since I keep getting lots of soft bans because of this. Is there a solution to solve the issue, so my character keeps staying in this location given i webspoof?

**Comment by otyler46** [comment]
I'm getting a similar issue. I am spoofing to NY and walking around and every once in a while the game will glitch and jump me back to my real location and cause me to get soft banned. Is anyone else experiencing this?

**Comment by winstein** [comment]
I found it to be more stable when I turn off my Cell-Data on my iPhone, with fewer jump-backs.

**Comment by otyler46** [comment]
i tried turning off data and only using my home wifi. however, i am still getting GPS jumping from my spoofed location to my home location and back quickly causing soft bans. I dont think i had this issue with the prior version.

**Comment by MoOx** [comment]
I am doing the opposite: turning off wifi and only use cell data and it seems I see less jump.

**Comment by iam4x** [comment]
Should be fixed in last release see #339
