### ISSUE TITLE
How to teleport all around the world

### ISSUE THREAD

**Issue by Truro** [iam4x/pokemongo-webspoof#325]
Hello guys !  Someone know how to teleport on the map ? I can't juste teleport myself on Europe but not in the USA, Japon, Africa, Australia.... 
I've got an error " Google can't schredule Trip " on Webspoof when I'm trying to go on central Park for example
 
It is possible or we are limited to our continent ? ?

Thx :)

**Comment by porkserver** [comment]
I have been able to Go to specific places around the world.  The trick is to Set your starting spot in the app map before launching Pokemon Go.  For example: I set my Long/Lat after launching to the desired location. Make sure you set the debug menu to simulate location: PokemonLocation  Then use the launch Pokemon Go link within the ios app.  Upon launch you should port to the desired start point within a couple seconds.  My bag full of Farfetch'd from Osaka speaks for itself.  (I am in Portland Oregon)

Another word to the wise.  I suggest logging out of your app at your home location before doing this That way the server potentially sees it as logging in from said location you've set.  You might also wait 8-12 hours between trips of this nature.  like they warn.  Fast movements and teleports could result in soft bans.

**Comment by Truro** [comment]
thanks you @porkserver  , but with your method  can we move with the arrow  in the web spoof app ?

**Comment by Truro** [comment]
beau

**Comment by porkserver** [comment]
Yes you can. I had great success moving around using the slowest speed.  The higher speed gave me random soft bans.  Just remember to give the app access to control computer in privacy preferences pane on your Mac.  Otherwise you will get click errors.

**Comment by firepower666** [comment]
Doset work at my PokemonGoWebspoof.. 
only get the Same massage with: Zero_Results

Cant set my location to another point, start all time at the same location..

**Comment by firepower666** [comment]
I Cant set up my location at Xcode.. but than I can't move.

**Comment by porkserver** [comment]
Don't use the search.  You need to look up the location on google maps and use the actually Lat/Long.  It's a bit of a pain but it works.

I will post a video tonight after work

**Comment by firepower666** [comment]
Thanks!

**Comment by Ladditron** [comment]
I would be interested in learning more about this too. Tried to teleport to Santa Monica from idaho but got caught and banned

**Comment by kebabortega** [comment]
@porkserver how can input the coordinates manually? is it in the project or the webspoof app in mac?

**Comment by iruy** [comment]
I don't understand how to do that. Whatever I input in the text field, report ZERO_RESULTS.
And I'm not allowed to edit thos lat/long fields, I can only delete and insert numbers, but not dots or minus

**Comment by iam4x** [comment]
keep discussion into #326
