### ISSUE TITLE
Unable to install "Pokemon WebSpoof"

### ISSUE THREAD

**Issue by firepower666** [iam4x/pokemongo-webspoof#330]
Hi, 

When I start PokemonGoWebSpoof, I got these massage from Xcode if I press Run. 

Unable to install "Pokemon WebSpoof"
The certificate used to sign "Pokemon WebSpoof" has either expired or has been revoked. An updated certificate is required to sign and install the application.

What should I do?

**Comment by bateller** [comment]
#336 #

**Comment by stefandunn** [comment]
Got the same issue, no way to fix it so it seems.

**Comment by iam4x** [comment]
Rename the bundle identifier, search through issues 👍
