### ISSUE TITLE
current location webspoof and actual location not the same

### ISSUE THREAD

**Issue by UXDesignerNL** [iam4x/pokemongo-webspoof#332]
Could there please come an update where you can set the location to the actual location of the phone? I got a softban because it literally transported me to another city (in this case; Amsterdam)... 

It also is really sensitive to any other application. It only spoofs the GPS of the pokemon go app while having the app opened. When you pull up or down anything else from both native elements as from apps like Whatsapp, it WILL switch back to the real location.

**Comment by iam4x** [comment]
Kill pokemon go before starting this 👍
