### ISSUE TITLE
Failing to open pokemon go from Xcode project

### ISSUE THREAD

**Issue by skilfoy** [iam4x/pokemongo-webspoof#333]
Here's the debug return that I'm getting when I click on the "Launch Pokemon GO" button in the program in my iphone:

2016-08-02 15:01:39.163 Pokemon WebSpoof[226:7114] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"

Any suggestions?

**Comment by firepower666** [comment]
#302

**Comment by iam4x** [comment]
Fixed in latest version.

**Comment by skilfoy** [comment]
Has anyone had any problems with the latest news from Niantic that they are doing permanent bans for people who spoof their location or use bots?
I really like this GPS spoof, but I'm not about to use it if I'm going to get banned.

**Comment by iam4x** [comment]
No problem for me @skilfoy
