### ISSUE TITLE
Failing to click/orientate the compass after a certain time on auto Pilote 

### ISSUE THREAD

**Issue by bbr21** [iam4x/pokemongo-webspoof#334]
Hi Guys,

When starting the autopilot mode, everything goes smoothly for a while but sometimes, the clicks on pokemon/pokestops and the orientation of the compass become impossible.
I can still click on my character / nearest pokemon / pokeball in the middle but that's it. I've to restart the game and the hack to make it works again  

Do you have any clue on this ?

Thanks a lot !

**Comment by iam4x** [comment]
Should be fixed with latest version.
