### ISSUE TITLE
Do I need to buy a developer account to use this app?

### ISSUE THREAD

**Issue by ChuanKing** [iam4x/pokemongo-webspoof#335]
There is a warning under General/Identity, which said "No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found." Even I rename the bundle and add my apple ID in the xcode I still cannot build the application.

<img width="996" alt="2016-08-02 10 31 37" src="https://cloud.githubusercontent.com/assets/11513221/17351959/f39c11cc-5900-11e6-9041-8385525a92ba.png">

this is the error message
<img width="999" alt="2016-08-02 10 32 59" src="https://cloud.githubusercontent.com/assets/11513221/17351978/1d4a298c-5901-11e6-8a6c-b2cd8c1573dc.png">

**Comment by bateller** [comment]
Just to expand on what @dcurletti said. You DO need an Apple Developer account (as he shows), but DO NOT need to pay the $99/yr fee for a full Apple Developer Account.
