### ISSUE TITLE
Stuck on the Launch Pokemon Go Screen

### ISSUE THREAD

**Issue by ryzo11** [iam4x/pokemongo-webspoof#336]
Go to click Launch Pokemon Go and I am given this message:

Pokemon WebSpoof[1375:610122] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"
2016-08-03 13:05:17.550 Pokemon WebSpoof[1375:610122] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"

I've tried reinstalling it but it doesn't work.

**Comment by bateller** [comment]
#330

**Comment by kennyfrance** [comment]
The updated pokomon go app has a new url scheme "com.googleusercontent.apps.848232511240-dmrj3gba506c9svge2p9gq35p1fg654p"

you can change the following in pokemon-webspoof : 

info.plist 
LSApplicationQueriesSchemes > item 0 > com.googleusercontent.apps.848232511240-dmrj3gba506c9svge2p9gq35p1fg654p

ViewController.m
static NSString * const kURLScheme = @"com.googleusercontent.apps.848232511240-dmrj3gba506c9svge2p9gq35p1fg654p://";

Good luck
Kenny

**Comment by lanabug** [comment]
@kennyfrance Where do i go in pokemon-webspoof to change those??

**Comment by mrgohamilton** [comment]
read #302

**Comment by kennyfrance** [comment]
When you open pokemon-webspoof. it will open Xcode.
Expand  pokemon-webspoof -> pokemon-webspoof
you should then see

ViewController.m
info.plist

Change those files

**Comment by geminiyellow** [comment]
how to start Pokemon-webspoof from source code?

**Comment by iam4x** [comment]
Should be fixed with latest version.
