### ISSUE TITLE
Unable to set a destination on LocationSpoof

### ISSUE THREAD

**Issue by overjoyed** [iam4x/pokemongo-webspoof#337]
![captura de tela 2016-08-03 as 10 20 51](https://cloud.githubusercontent.com/assets/20816760/17366912/0af79004-5964-11e6-8fae-8136edb94964.JPG)

When I try to set a destination on LocationSpoof I keep getting the same errors

**Comment by MattFlood7** [comment]
I am also experiencing the same issues.
