### ISSUE TITLE
No pokemonLocation in Debug -> Simulate Location

### ISSUE THREAD

**Issue by yepes** [iam4x/pokemongo-webspoof#34]
Hi!

I'm trying to run this, but there's no pokemonLocation in my Simulate Location option.

I've added the app to my accesibility list:
https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233140361

I'm on El Capitan (latests) and Xcode (latest).

I'm sure I'm missing something. Is this happening to anyone else?

Thanks

**Comment by iam4x** [comment]
Can you try this: https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874

**Comment by yepes** [comment]
awesome! working now!
