### ISSUE TITLE
webspoof does not work

### ISSUE THREAD

**Issue by aRollingStone** [iam4x/pokemongo-webspoof#345]
Hello first of all, thanks for everything you did so far. I enjoyed playing when I have to be home. recently it stopped moving giving 
/Users/Seray/Desktop/pokemongo-webspoof-darwin-x64/pokemongo-webspoof.app/Contents/Resources/app/autoclick.applescript:55:187: execution error: System Events got an error: osascript is not allowed assistive access. (-1719)

**Comment by TaciteOFF** [comment]
Go to system preferences, security, confidentiality, accessibility and tick the boxes.
