### ISSUE TITLE
Bike (Arround 18 km/h) is to fast to hatching eggs

### ISSUE THREAD

**Issue by elvquant** [iam4x/pokemongo-webspoof#346]
Yesterday I tried to hatching eggs on bike and no distance added at the app. I read today, that 16km/h is the limit to hatching eggs. Is it able to change the speed?

**Comment by kenzo23312** [comment]
1

**Comment by bateller** [comment]
I recommend a box where you can enter your own km/h value

**Comment by macdonjo** [comment]
Code it in @bateller or @elvquant

**Comment by elvquant** [comment]
Cannot find the Location in files!

**Comment by chris249** [comment]
If you open the autopilot.js file located in src/views/map you'll see all the travel modes listed, just change the number 18 to 14/15 and save. Then run the program again. This has to be tested, will try tomorrow, as it is 12.16 am right now

**Comment by elvquant** [comment]
Don't know, why I haven't found it?
I had to change on:
- app/dist/index.js
- app/src/views/maps/autopilot.js

Tested and it works as expected.

**Comment by sneeekk** [comment]
Hi,
i also changed here
app/dist/index.js
app/src/views/map/autopilot.js
after that the webspoof is emty, without a map .
i changed it via text edit

**Comment by chris249** [comment]
Have you saved it back to a .js file?
And make sure you only changed the numbers, not the rest of the code. 

Met vriendelijke groet,

Chris de Groot

**Comment by sneeekk** [comment]
yes i did, but i will check it again to be sure for the .js file

**Comment by chris249** [comment]
Let me know if this is the problem, otherwise I'll upload my code for you to download. 

Met vriendelijke groet,

Chris de Groot

**Comment by sneeekk** [comment]
first i changed the autopilot.js and tested the spoof and the map was visible.
the i changed the index.js only bicycle 18 to 13 and after that no map :)
both files are still .js

so it didnt work

**Comment by chris249** [comment]
When I get home I'll create a gist with the working index.js

**Comment by sneeekk** [comment]
thank you :)

**Comment by chris249** [comment]
Here you go:
https://gist.github.com/chris249/b5d745c66ba439fa2bc21b8d6e71025d

Just copy and paste it into dist/index.js

**Comment by sneeekk** [comment]
great it works :)

**Comment by chris249** [comment]
Great to hear!
