### ISSUE TITLE
unable to install 'pokemon webspoof'

### ISSUE THREAD

**Issue by aRollingStone** [iam4x/pokemongo-webspoof#348]
this is what i get when i try to start the app. '''''The certificate used to sign "Pokemon WebSpoof" has either expired or has been revoked. An updated certificate is required to sign and install the application.'''' please help me if you know the solution

**Comment by LegalizeMilk** [comment]
You will have to change the name under General>Bundle Identifier in Xcode and it will work. You can put whatever you like in there 👍

**Comment by iam4x** [comment]
Dup
