### ISSUE TITLE
Feature Request: Minute Movement of Lat/Long when Stationary

### ISSUE THREAD

**Issue by bateller** [iam4x/pokemongo-webspoof#349]
**Issue:**
When standing still, GPS signals always change, even if they are minute changes (unless no signal at all is detected). This is due to receiving differing signal strength from differing GPS satellites (since they are NOT geostationary and due to timing), cloud cover or other changing interference. When monitoring GPS of a stationary device you would expect to see slight movement in the Lat/Long reading even if its only in the millionths place or ten-millionth, etc. This would be virtually invisible on devices that round up to higher decimal place (most round to one millionth or one hundred-thousandth where a couple meter differentiation doesn't matter and the accuracy begins to falter anyway), but the data seems to be somewhat monitored by Niantic due to the problem listed below.

**Problem In Game:**
If I try to sit around a group of PokeStops to receive items... and if I sit too long at the exact same coordinates, I will get a "Try Again Later" message. If I move a little, I'll immediately be able to receive items. Without using the PokemonGo Webspoof (and relying on 'real' GPS signals) this issue does not arise.

I worry this could lead to a SoftBan if Niantic starts to monitor accounts where the Lat/Long stays exactly the same for periods of time.

**Proposed Solution:**
When no autopilot is active, move the Lat/Long GPS signal randomly (or by an interval) in the  hundred thousandths or millionths place. Thus more accurately 'spoofing' a GPS signal.

**Comment by boom-time** [comment]
This is a very nice write up for saying "Add Jitter"  😆 

I've already added this to my code and you're right it is much better having the guy jitter around a little when standing still.

I'll try and add this feature as my first PR

**Comment by bateller** [comment]
#358 pull req addresses this issue

**Comment by bateller** [comment]
Addressed in #339 . Closing this.
