### ISSUE TITLE
Xcode won't allow me to simulate the location

### ISSUE THREAD

**Issue by nathankrish** [iam4x/pokemongo-webspoof#350]
![screen shot 2016-08-05 at 4 17 08 pm](https://cloud.githubusercontent.com/assets/11147766/17449406/304a1ca8-5b28-11e6-87c7-817f91be859f.png)

**Comment by ferazambuja** [comment]
Is the app running on your phone?

**Comment by RSGC-LOWRY-J** [comment]
open the webspoof app and run pogo, then exit and close them both.

After that, go to Product > Run and it should open the webspoof on your phone

With the app still open, set the location

**Comment by iam4x** [comment]
@nathankrish You to run the project first like @RSGC-LOWRY-J said!
