### ISSUE TITLE
Webspoof app not running pokemon go

### ISSUE THREAD

**Issue by RSGC-LOWRY-J** [iam4x/pokemongo-webspoof#351]
when I open the webspoof and press the "Launch Pokemon Go", nothing happens, and xcode comes up with this:

2016-08-05 20:22:36.175 Pokemon WebSpoof[276:15414] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"

it probably has something to do with the update that removed pokesteps and low power mode, as it was working before that.

**Comment by dawin09** [comment]
same issue

**Comment by rainbowhat** [comment]
same

**Comment by b-admike** [comment]
@RSGC-LOWRY-J @dawin09 @rainbowhat you might not have this commit https://github.com/iam4x/pokemongo-webspoof/commit/f5ff9656217e64ca67e767cde71ff3059c14fbc5. I also was running into the issue, but got past it by modifying the files myself.

**Comment by dawin09** [comment]
@b-admike it worked fine, thanks bro

**Comment by rainbowhat** [comment]
@b-admike  is there anyway i can do it without having to do this eveyrtime i want to run it?

**Comment by b-admike** [comment]
@rainbowhat yeah I did the following (close the app if it is running):
1) go to the location of the app in Finder
2) right-click on the app, click `Show Package Contents`
3) Go to `Contents -> Resources -> app -> xcode-project -> pokemon-webspoof` and modify `viewController.m` and `Info.plist`

**Comment by iam4x** [comment]
Should be fixed with last version.
