### ISSUE TITLE
Iphone is ineligible?

### ISSUE THREAD

**Issue by aidenmarcelis** [iam4x/pokemongo-webspoof#357]
I have an iPhone 5s running ios 9.3.2 and for some reason my phone shows up on the list as "ineligible", any ideas?

**Comment by ngoclt** [comment]
What is your Xcode version, should download the latest version from App Store anyway.

**Comment by aidenmarcelis** [comment]
Yeah that was the fix, should've closed this earlier. Thanks anyway.
