### ISSUE TITLE
Niantic patched spoofing?

### ISSUE THREAD

**Issue by Aqquamarine** [iam4x/pokemongo-webspoof#359]
Pokemon Go was updated for iOS today and the webspoof app has not worked since. I was able to travel to a different location, but the game instantly soft banned me even though I used the same methods that I have been using to keep myself from getting banned in the past. (By the way, if you don't know what a softban does, it basically just makes you unable to get items from pokestops and pokemon run away immediately). Has anyone else been having major issues with the program since the update? Also, does it make a difference that I'm still on iOS 9.3.3?

**Comment by giladcohen** [comment]
Check out a solution for this in issue #339.

**Comment by Aqquamarine** [comment]
@giladcohen thanks, appreciate the help.
