### ISSUE TITLE
can't get menu bar 1 of process "xcode". Invalid index. (-1719)

### ISSUE THREAD

**Issue by RobSim** [iam4x/pokemongo-webspoof#36]
> /app-path/Contents/Resources/app/autoclick.applescript execution error : System Events got an error: can't get menu bar 1 of process "xcode". Invalid index. (-1719)

I'm not sure what the issue is here. Mac OSX 10.11.5, latest public iOS, Xcode from app store.

**Comment by flaviosa** [comment]
I have the same issue.

**Comment by pyro2927** [comment]
I was seeing similar things, but you can get around this by manually clicking the menu item in Xcode (that's all the `applescript` is trying to do):
![2016-07-18 at 10 30 pm](https://cloud.githubusercontent.com/assets/39943/16937754/5f5cf1d6-4d37-11e6-95d0-7495b0e19226.png)

**Comment by iam4x** [comment]
Thank's a lot for the screen @pyro2927 👍
