### ISSUE TITLE
PokemonGo don't to real location after close pokemon webspoof

### ISSUE THREAD

**Issue by henriquesacramento** [iam4x/pokemongo-webspoof#363]
PokemonGo don't to real location after close pokemon webspoof.
How i can back to real location?

**Comment by wwwchrisde** [comment]
Also had the issue - I killed the webspoof app on iPhone - didn't work but a reboot of the device will set you back to your real location

**Comment by g3zhouqu** [comment]
@henriquesacramento , you just need to quit simulation before you close Pokemon go.

**Comment by Aqquamarine** [comment]
Either rebooting your device or resetting all of your settings will set your location back to normal.

**Comment by iam4x** [comment]
Reboot your device it's the easiest way 👍
