### ISSUE TITLE
how can i add coords to the program ? 

### ISSUE THREAD

**Issue by iLoveMax** [iam4x/pokemongo-webspoof#365]
Hi. Its still working after the latest update and i can walk around my town from the desk at my work. 👍

With the Shutdown of Pokevision new sites like https://pokezz.com came up. 

How can i add the coords to the programm ?

**Comment by hpnishi** [comment]
good question. Cant CRTL V and writing the coords is not working. Cant add negative -

**Comment by ngoclt** [comment]
I'm actually working on this issue right now. Will let you know the result soon.
However, using this trick will be a risk for being banned. :)

**Comment by iam4x** [comment]
Do not jump to locations like this you will be banned.
