### ISSUE TITLE
New URL for v1.3.0?

### ISSUE THREAD

**Issue by ycho168** [iam4x/pokemongo-webspoof#368]
Is the URL updated for v1.3.0 again? Launch pokemon go is reporting failed for URL again
Thanks

**Comment by Takage** [comment]
1.3 ?

**Comment by zerobyt** [comment]
URL for 1.3.1 please :(

**Comment by nickg819** [comment]
Why don't you just open it on your own?

**Comment by Takage** [comment]
1.3? there is no 1.3 release

**Comment by iam4x** [comment]
fixed with last release https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.1
