### ISSUE TITLE
Issues on the last step

### ISSUE THREAD

**Issue by Airhammer26** [iam4x/pokemongo-webspoof#369]
I just downloaded everything and made it almost work.
Just having issues on the last step, because when I change my location and walk through a town close by my home, every time I'm not actually moving, my character jumps back to my current location. Also i receive some errors while walking (1719 and so) but was able to catch pokemon and spin pokestops... But still I will never be able to play long, because it always sets me back to my actual location.
I just got soft banned because of that.
Anyone else has the same issue? 

Cheers
Airhammer

**Comment by iam4x** [comment]
There's no easy fix to it, it's a duplicated of a known issue. The best to do is to switch back to `pokemongo-webspoof` iOS running app every ~3 minutes.
