### ISSUE TITLE
Pokéstops: medal is spinning but no Ball is gained

### ISSUE THREAD

**Issue by tongatron** [iam4x/pokemongo-webspoof#37]
Pokéstops doesn't works for me: I can spot them and let the medal spin, but when the medal stops spinning it won't give any Balls bonus.

**Comment by james-145** [comment]
This is a soft ban, probably because you travelled too far of a distance too quickly, its happened to me before, wait 30 minutes and try again

**Comment by stefan-o** [comment]
Sometimes it can take up to 3 hours

**Comment by tongatron** [comment]
Thank you for the answers...I'll wait!

**Comment by MoOx** [comment]
It can also be a server downtime.
