### ISSUE TITLE
Can't teleport outside Europe

### ISSUE THREAD

**Issue by chris249** [iam4x/pokemongo-webspoof#370]
When I enter a location outside Europe, let's say New York, I've got a response saying Zero Results. Inside Europe every location works.

Anyone got a fix for this?

**Comment by powhu** [comment]
Because API cannot route Europe to New York.
You need edit lat,lng to U.S then try again.

**Comment by chris249** [comment]
What is the best way to enter the coordinates? If Intry to enter a "." it won't work (like 35.748273). I can only enter the first two numbers without problem. Or is that also the solution?

**Comment by powhu** [comment]
Enter 35 then use arrow keys.

**Comment by chris249** [comment]
Works like a charm! Thanks @powhu
