### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by nvcken** [iam4x/pokemongo-webspoof#372]
Downloading electron-v0.4.1-darwin-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v0.4.1/electron-v0.4.1-darwin-x64.zip returned 404
Failed to find Electron v0.4.1 for darwin-x64 at https://github.com/electron/electron/releases/download/v0.4.1/electron-v0.4.1-darwin-x64.zip

**Comment by ngoclt** [comment]
Hey @nvcken,

To resolve this, check @b-admike's solution here: https://github.com/iam4x/pokemongo-webspoof/issues/364

**Comment by iam4x** [comment]
Hey @nvcken this is fixed on master branch 👍
