### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by Thatguywill** [iam4x/pokemongo-webspoof#373]
Ive had a read through of the past issues but can seem to see a clear answer for the issues I'm having. Im running iOS 10 on Xcode 8 and I'm not a developer.

The 3 issues pop when pressing build:
- An App ID with Identifier 'poke' is not available. Please enter a different string.
- No profiles for 'poke' were found
- Code signing is required for product application in SDK iOS 10

**Comment by iam4x** [comment]
1. app id -> change it to something unique
2. no profiles -> makes n1 working then hit "Fix Issues"
3. code signing -> need an apple developer account to use beta iOS10

Look through issues it's a duplicated question.
