### ISSUE TITLE
Can't open URL?

### ISSUE THREAD

**Issue by CallumRocks** [iam4x/pokemongo-webspoof#374]
Once Xcode opens the Pokemon WebSpoof app and I tap "Launch Pokemon GO" I receive this error;
"The operation couldn’t be completed. (OSStatus error -10814.)".
Happens each time I tap, Pokemon Go does not launch. 

Any solution?

**Comment by nickg819** [comment]
Yea. Open it manually. Don't use the link in the spoof app.

**Comment by iam4x** [comment]
fixed with last release https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.1
