### ISSUE TITLE
An App ID with Identifier 'com.iam4x.oak' is not available. Please enter a different string.

### ISSUE THREAD

**Issue by joeandkris** [iam4x/pokemongo-webspoof#378]
An App ID with Identifier 'com.iam4x.oak' is not available. Please enter a different string.

I get this error no matter what I change the bundle identifier to. Please help!

**Comment by benjaminhallock** [comment]
Did you read the instructions?

**Comment by joeandkris** [comment]
Yes I followed them.

**Comment by gbernal** [comment]
read them again 
Rename the Bundle Indentifer to something unique and different (for example com.[yourgithubname].pokemon-webspoof - you need it after an update)

**Comment by joeandkris** [comment]
I did that. I've named it com.[example].pokemon-webspoof and
com.iam4x.[example] and just [example]. Nothing works. There is always an
error. I've watched multiple YouTube videos on this and follow them
exactly. I saw in another issues thread there being something in the
accounts settings? Am I suppose to add something there?

**Comment by gbernal** [comment]
You misunderstood the example. There is no need for brackets. 
make it 

something like this com.nobrackets.pokemon-webspoof

**Comment by joeandkris** [comment]
I didn't misunderstand. I used the brackets to show where I added
something. For example I tried com.test.pokemon-webspoof and
com.tutorial.pokemon-webspoof. Same results. Then I tried com.iam4x.oak
from one of the forums on your site. Then com.oak.pokemon-webspoof.

**Comment by Pottypotsworth** [comment]
Did you try clicking the "Fix this error" after changing the name?

**Comment by joeandkris** [comment]
Yes. The error message comes up after it tries to fix it.

**Comment by winstein** [comment]
I changed it to com.aboutwinston.pokemon-webspoof and it worked for me

**Comment by iam4x** [comment]
Change it to something unique like: `com.joeandkris.pkm`
