### ISSUE TITLE
Pokemon WebSpoof[3529:1181804] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"

### ISSUE THREAD

**Issue by edisonkam** [iam4x/pokemongo-webspoof#379]
what is this ? 

Pokemon WebSpoof[3529:1181804] -canOpenURL: failed for URL: "b335b2fc-69dc-472c-9e88-e6c97f84091c-3://" - error: "(null)"

**Comment by arizonahockey** [comment]
This is (was) the url scheme used to open PokemonGO from the spoof app. Looks like it has changed. I followed the guide here: https://www.reddit.com/r/workflow/comments/2tlx29/get_url_scheme_of_any_app/
then replaced the error'd URL with the one from the new download, and was able to open PokemonGO from this app, but it's still not working for me.

**Comment by iam4x** [comment]
fixed with last release https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.1
