### ISSUE TITLE
skipping file '/var/folders/x3/y8v90wyn1sdgrk65cp7xhk6h0000gn/T/tmp-19419HELcuhF2LV33/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

### ISSUE THREAD

**Issue by FrancisZamora** [iam4x/pokemongo-webspoof#38]
can't simulate pokemonlocation.gpx because the file is being skipped

**Comment by DannyPeo** [comment]
Build and run the current scheme in Xcode. Then move to a location you want to be on the pokemongo-webspoof (also running on your mac.) This should now mean the pokemonlocation.gpx in Xcode is no longer red. In Xcode go to Debug - Simulate location and select pokemonLocation. Launch Pokemon Go on iPhone and all should be good. 

You will always get an error regarding the gpx file until you have built and moved to a location on the app.

**Comment by iam4x** [comment]
This is only a warning, you can skip. It will be fixed in 1.1.0 👍

**Comment by Hack4Life** [comment]
> Then move to a location you want to be on the pokemongo-webspoof
What exactly do you mean?
