### ISSUE TITLE
map api not working no result for lat long for a place

### ISSUE THREAD

**Issue by umairahmed3** [iam4x/pokemongo-webspoof#380]
on starting the app there is a prompt saying googleapis returned error 403
![image](https://cloud.githubusercontent.com/assets/12157586/17641702/f736117a-6148-11e6-867c-361eb048071b.png)

and on entering any destination there is a red prompt saying no result

![image](https://cloud.githubusercontent.com/assets/12157586/17641705/18a1ed84-6149-11e6-9232-ab8ab7e45029.png)

**Comment by umairahmed3** [comment]
this works when entering a destination in Europe and India but not any place else.

**Comment by iam4x** [comment]
* I'm having problems with geolocation also, might a temporary issue I can't do anything about it.
* For the ZERO_RESULTS => No physical route is found, it's a bug should be doable with teleporting.

**Comment by iam4x** [comment]
Follow discussion into #326
