### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dualshote** [iam4x/pokemongo-webspoof#381]
Hey :) It's possible to have a new release with all fixes :)

**Comment by airliner1975** [comment]
... would be great!
Or would someone PLEASE can give me an idiot-safe step-by-step instruction on how to get all the fantasic changes you guys made to work?
Its hard for me, not only english isn't my mothertounge, but no matter what I download an try, I only get the same version an cannot see any changes.
Thanxx a lot!

**Comment by dawin09** [comment]
yes, this would be great :)

**Comment by Cory-Bennett** [comment]
+1

**Comment by iam4x** [comment]
https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.2.1

**Comment by dualshote** [comment]
Thx @iam4x :)
