### ISSUE TITLE
Running Two Instances of Program

### ISSUE THREAD

**Issue by pokemongo327** [iam4x/pokemongo-webspoof#383]
Is it possible to run two instances of this at once? i.e plugging two phones into on mac computer and running it on both at the same time? If so could someone explain how?

**Comment by reactortrip** [comment]
I wouldn't do it, heck it's not worth it to do one til we learn more about how it is banning ingress players.  You will just be retroactively banned once they get that all up and running.

**Comment by iam4x** [comment]
duplicated of #101
