### ISSUE TITLE
Unable to "npm run dev"

### ISSUE THREAD

**Issue by Cory-Bennett** [iam4x/pokemongo-webspoof#385]
Hey team,

I'm getting this error when I enter npm run dev

`npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-jsx-a11y@2.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint-plugin-jsx-a11y@^1.2.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Documents/GitHub/pokemongo-webspoof/npm-debug.log`

**Comment by iam4x** [comment]
@Cory-Bennett Use npm^3

`$ npm i -g npm`
