### ISSUE TITLE
I can't travel without re-checking /Debug/Don't simulate location & /pokemonLocation

### ISSUE THREAD

**Issue by G1tGudNub** [iam4x/pokemongo-webspoof#39]
And when i do this i'm sent to my real location so i'm kinda fcked...
Sorry english is not my native language (french is) but i'll try my best to explain myself if i need to

**Comment by G1tGudNub** [comment]
btw this app is awesome

**Comment by iam4x** [comment]
Explique moi le problème en français :) Je vais fermer l'issue pour pas déranger le reste.

**Comment by G1tGudNub** [comment]
Le problème s'est résolu de lui même en relançant l'app 
merci d'avoir fermé l'issue et pour l'app
