### ISSUE TITLE
Cannot move across ocean

### ISSUE THREAD

**Issue by alexpearce92** [iam4x/pokemongo-webspoof#395]
I am running into a "ZERO RESULTS" error when trying to select a location across an ocean to which to teleport. Ex. California to Japan.

**Comment by Rutch** [comment]
You need to punch in the latitude/longitude manually to move to other continents.  It also only seems to like whole numbers when you're manually inputing them.  For example if I want to go to Tokyo (35.70861/139.73304) I'd stick in 35/139 and that would at least get me into Japan, then I could drag the map to Tokyo and teleport there.

**Comment by alexpearce92** [comment]
That worked, thanks
