### ISSUE TITLE
check dependencies

### ISSUE THREAD

**Issue by anushkmittal** [iam4x/pokemongo-webspoof#4]
Check dependencies

warning: skipping file '/var/folders/j6/m3mn38dj3lq6fqg4r7nnn25c0000gn/T/tmp-160373TpZ2ZkVSOlp/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

**Comment by stefan-o** [comment]
I ended up creating my own gpx file and added it to the project.

**Comment by iam4x** [comment]
Fixed into v1.1.0 https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.0
