### ISSUE TITLE
Keep spawning at original gpx location

### ISSUE THREAD

**Issue by DannyPeo** [iam4x/pokemongo-webspoof#40]
I'm not sure if this is a Pokemon Go server issue or not. Once i have been moving around for a while (either by using the arrow keys or by dragging with the mouse) the game will spawn me back to the original location i was when i started the app. When this happens if i move locations again it will spawn me to that location shown on my mac. I'm only moving small amounts at a time so it's not a soft ban issue.

Was just wondering if there was a fix or if anybody else is experiencing this issue. Apart from this the app is great and really helped out, i can't wait for the auto pilot to be released.

**Comment by betokas** [comment]
I have the same issue on my Iphone 6 running IOS 10, after stay few minutes on a place, the app return to original position.

**Comment by iam4x** [comment]
This will be fixed in 1.2.0 version, out soon. See https://github.com/iam4x/pokemongo-webspoof/commit/de0e7b6966cb171a4c6404070afe83f1fa49b3d5
