### ISSUE TITLE
New issue since iOS 10

### ISSUE THREAD

**Issue by gingerrob1986** [iam4x/pokemongo-webspoof#409]
Anyone else getting this? I'm doing everything as before, but get this message, any ideas?
![screen shot 2016-09-15 at 19 39 32](https://cloud.githubusercontent.com/assets/20751397/18562597/491488a8-7b7c-11e6-966a-2bf72dcb0f6d.png)

**Comment by MoOx** [comment]
You need to update Xcode to latest version. I got this in the past. Upgrading fixed it.
Be sure to have latest Xcode and iOS (I guess for iOS it's good).
