### ISSUE TITLE
Run Dev not functional

### ISSUE THREAD

**Issue by eq2kazial** [iam4x/pokemongo-webspoof#412]
@iam4x 
Updated to latest Dev build tonight and the Electron console doesn't work. This error appears in terminal:

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         options: {
           postcss: ...
         }
       })
     }

**Comment by MoOx** [comment]
Related to this https://github.com/webpack/webpack/issues/3018.
For postcss the solution is to move the configuration to a plugin

```js
    plugins: [
      // You should be able to remove the block below when the following
      // issue has been correctly handled (and postcss-loader supports
      // "plugins" option directly in "query")
      // https://github.com/postcss/postcss-loader/issues/99
      new webpack.LoaderOptionsPlugin({
        test: /\.css$/,
        options: {
          postcss: previousPostCSSPluginsFunction,
          // required to avoid issues with other loader (eg: css-loader?modules)
          // this is normally the default value, but when we use
          // LoaderOptionsPlugin, we must specify it again, otherwise,
          // context is missing (and css modules names can be broken)!
          context: __dirname,
        },
      }),
```

**Comment by tselincoln** [comment]
where should I place the plug in? which file?

**Comment by MoOx** [comment]
See #413 for the fix ;)
