### ISSUE TITLE
Could not find developer disk image

### ISSUE THREAD

**Issue by pokemon-go78** [iam4x/pokemongo-webspoof#414]
On an iPhone 7 Plus with iOS 10.0.2 the following error occurs while "build":

No trait information  for iPhone 9,4

When I advise xcode to "run", it says:

Could not find developer disk image

Is anybody aware of this issue? Any solutions on hand?

**Comment by MoOx** [comment]
> Could not find developer disk image

This means that your Xcode is out of date and/or doesn't have the proper corresponding image disk (ie: iOS files corresponding to your iPhone iOS version).

So try updating Xcode.
