### ISSUE TITLE
error autoclick xcode - code 2

### ISSUE THREAD

**Issue by pokemon-go78** [iam4x/pokemongo-webspoof#415]
Hi!

I was trying to run the webspoof on an iPhone7 Plus.

It launched, but when I tried to move the character, the following error showed up:

Desktop/pokemongo-webspoof-darwin-x64/pokemongo-webspoof.app/Contents/Resources/app/autoclick.applescript:55:187: execution error: „System Events“ hat einen Fehler erhalten: osascript hat keine Berechtigung für den Hilfszugriff. (-1719)

in english:
(System Events received an error: osascript has no permission for the helpaccess)

Any ideas?

**Comment by MoOx** [comment]
Looks like a dup of https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233106899
