### ISSUE TITLE
Error getting geolocation

### ISSUE THREAD

**Issue by lswlhnzhuce** [iam4x/pokemongo-webspoof#416]
Somehow this happens after I upgraded Xcode to 8.0 two days ago. When start Wedspoof, it gives the following error
<img width="660" alt="screen shot 2016-09-24 at 12 43 55 pm" src="https://cloud.githubusercontent.com/assets/22417105/18809841/fcb03996-8254-11e6-8b23-8428bf32edb3.png">
Then it re-locate me to the middle of Japan.
<img width="801" alt="screen shot 2016-09-24 at 12 44 05 pm" src="https://cloud.githubusercontent.com/assets/22417105/18809845/0cfd27aa-8255-11e6-9a6e-d8f7bbe22599.png">

**Comment by iam4x** [comment]
Wontfix, it's google maps geolocation service which is not working. I can only guess some position from your IP after.
