### ISSUE TITLE
Use and Activity, Ban reports? Safety measures?

### ISSUE THREAD

**Issue by thatsweater** [iam4x/pokemongo-webspoof#424]
Just wondering about this, does anyone still use this? What are the best methods of not getting banned?

I assume to turn wifi off, simulate in your own town/from your house and adhere to speed limits... Have you been banned? What have you done to prevent it?

Thanks

**Comment by iam4x** [comment]
Act as you play or move normally (no jump to location, but moving at 130km/h works to reach a place) and you won't been banned 👍

**Comment by chasetb** [comment]
I use it almost daily and have not been banned. I only use teleport as a starting location and wait at least 8 hours before teleporting to somewhere far away or coming back to my actual GPS coordinates.

**Comment by thatsweater** [comment]
I haven't seen this anywhere, but does this accurately do altitude? And are locations and routes randomized by whatever small fractions look correct?
