### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jordygroote** [iam4x/pokemongo-webspoof#44]
can;t sping poke stops and every pokemon i encounter jumps from ball and then runs away/ dissappears, gyms glitches out and back to start screen

**Comment by octalmage** [comment]
You got soft banned, don't jump far away. Just walk like you would in real life. The ban will only last  a couple of hours.

**Comment by jordygroote** [comment]
Confirmed, i tried this morning worked like a charm, thanks for this program!
