### ISSUE TITLE
Suspended!

### ISSUE THREAD

**Issue by evansgo** [iam4x/pokemongo-webspoof#451]
A warning for people, I've been using webspoof for a couple of years now with no issue, but recently I got the red warning screen on my main account. So I hardly used it for a while, but still got the next suspend screen. All this time I have an alt account using pokego++ on another phone and I'm spoofing all over the place with no detection.  So it seems as is something has changed and webspoof is no longer 'safe'.

**Comment by GitHubber78** [comment]
Same thing here, used it for 2 years without any issues, but all out of a sudden, day 1 = red notification, day 2 without webspoof still the notification, day 3 = suspended.

Anything here who can look into that? Any chance to make the webspoof "invisible" again?

**Comment by Diegononea** [comment]
Same here, got me shadow ban and red warning on all accounts, idk if the issue is Xcode itself or the Pokemon Webspoof thing.

**Comment by dmoritz9** [comment]
All 4 of my accounts were also banned.  Staying tuned here hoping to find out the cause and hopeful for resolution.

**Comment by evansgo** [comment]
I got the second suspension for max two snipes many hours apart, so def not from abuse

**Comment by GitHubber78** [comment]
So it seems to be a general issue instead of too excessive usage / spoofing.

Hmmm.

Any ideas, guys?

**Comment by dmoritz9** [comment]
I've heard a couple of theories, but that is all they are....
1.  Xcode does report altitude changes.  Is this even true?  Can it be modified?
2.  Running the same GPX route.  I didn't run any GPX routes, but I do mostly let WebSpoof walk in the same areas.
3.  Standing ABSOLUTELY STILL with no GPS drift.
4.  Something about the local wifi of the device being in a different location than the GPS coordinates.

Again, these are just theories that I have seen floated.  I have no idea if any are true.

**Comment by JeepTravelAtWorld** [comment]
For the last week, I've got the red warning every day without doing nothing. I remove the Web spoofing apps on my iPhone.

**Comment by pxhll** [comment]
The red warning can come without spoofing, and it last for about 10 days.

**Comment by iam4x** [comment]
This is not safe anymore, I will update the README. Thanks for the heads up guys 👍
