### ISSUE TITLE
Does the introduction of Adventure Sync make this not safe?

### ISSUE THREAD

**Issue by woftis** [iam4x/pokemongo-webspoof#459]
I know officially this is marked as not safe, although I've been using for a few years now without any sort of ban or warning (always start from my house, never teleport etc.)

Will adventure sync catch users out now if their device steps usage etc. doesn't match up with PoGo?

**Comment by trisapple** [comment]
It’s hard to give a definite answer for now given that the Adventure Sync has been available for 2 days now. 

Till now, nothing has happened to my account.
