### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by g3crossfire** [iam4x/pokemongo-webspoof#48]
in terminal put in this 
$ git clone git@github.com:iam4x/pokemongo-webspoof.git

got this error

Cloning into 'pokemongo-webspoof'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by efarem** [comment]
Looks like theres an issue with your Github ssh key.

**Comment by KostyaChoporov** [comment]
@g3crossfire use zip release instead of clone repo :)

**Comment by iam4x** [comment]
It's more likely an issue with your git configuration:

https://help.github.com/articles/error-permission-denied-publickey/
