### ISSUE TITLE
Load App onto iPad and blank

### ISSUE THREAD

**Issue by Garguy** [iam4x/pokemongo-webspoof#53]
When I run webspoof after opening PokemonGo I just get a white screen. Nothing to click for gps so the gpx file is still blank. Do I need to create the gpx myself or am I trying to load the wrong part of the app onto the device?

**Comment by KostyaChoporov** [comment]
@Garguy, Before build xcode project press button "Auto update Xcode location" in main window.

**Comment by Garguy** [comment]
@KostyaChoporov I am unable to find the "Auto update Xcode location" button anywhere within Xcode ide

**Comment by iam4x** [comment]
@Garguy It's located onto the Mac application `pokemongo-webspoof.app`

See https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874 for more explanation 👍
