### ISSUE TITLE
I get a error message if I want to move on the map

### ISSUE THREAD

**Issue by Zottel33** [iam4x/pokemongo-webspoof#55]
Hi,

I get a error message if I want to move on the map and the "Auto update Xcode location" button is activated.

I use the german languare on my Mac.

This is the Error code:

Error autoclick Xcode - Code 2
/Application/pokemongo-webspoof.app/Contents/Resources/app/autoclick.apples
execution error: "System Events" hat einen Fehler erhalten (it means: get an error) "menu item "pokemonLocation" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode"" kann nicht gelesen werden (it means: can not read). (-1728)

If you need more informations please tell me.

**Comment by iam4x** [comment]
Check https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874 please 🙏 

And read known issues https://github.com/iam4x/pokemongo-webspoof#known-issues
