### ISSUE TITLE
pokemonLocation.gpx doesn't work

### ISSUE THREAD

**Issue by Pokegopla** [iam4x/pokemongo-webspoof#56]
I have followed all steps and provided on my mac and iPhone all privileges to the apps. And still it stays red in Xcode and doesn't show up in the list of location simulations. 

Perhaps anyone can help me?

**Comment by Pokegopla** [comment]
Sorry I didn't yet read the known issues.. Let me try that first.

**Comment by CrazyJayson** [comment]
just jump a little on the map with holding down left click with your mouse and it should appear (should work with arrow keys too)

**Comment by Pokegopla** [comment]
Oké thanks worked 👍
