### ISSUE TITLE
Arrows dont work

### ISSUE THREAD

**Issue by DogKillerRj** [iam4x/pokemongo-webspoof#57]
Hello. I made all the tutorial, and all works fine. I appear in the location when I search (i jump for sydney.. new york..) but when I try click in the arrows, the pokeball moves but nothing do in the pokemon go.. I`m doing something wrogn?

* Sorry for my mistakes in english.. its not my mother language :(

**Comment by CrazyJayson** [comment]
just jump a little on the map with holding down left click with your mouse and it should appear (should work with arrow keys too)

**Comment by aekanman** [comment]
The movement that you make with the arrows is quite small. So there's a chance that you're too zoomed out and not seeing the movement. Zoom in to see your moves and don't jump to too many places to not banned. Alternatively, you can use the keyboard arrows.

**Comment by iam4x** [comment]
@DogKillerRj Don't jump that far that's why 👍
