### ISSUE TITLE
Error autoclick Xcode - code 2

### ISSUE THREAD

**Issue by sagestein461** [iam4x/pokemongo-webspoof#6]
![screen shot 2016-07-15 at 9 19 40 pm](https://cloud.githubusercontent.com/assets/20485684/16892723/eeb7e97a-4ad1-11e6-9d6d-2f403d434206.png)

**Comment by g3crossfire** [comment]
Im getting the same error. would love to know how to fix.

**Comment by iam4x** [comment]
dup of #5
