### ISSUE TITLE
Cant Simulate Location

### ISSUE THREAD

**Issue by NevadaJack** [iam4x/pokemongo-webspoof#60]
Whenever I get to the simulate location step all of the selection is grey and cant be selected

**Comment by ziperof** [comment]
Same issue here. Have followed the other suggestions in threads re: selecting accessibility settings. Not sure what I'm missing.

**Comment by muescha** [comment]
maybe this
- try to move a little in the app
- see hint at [#5:comment](https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233739078)

**Comment by iam4x** [comment]
If every choices are grey like this:
![screen shot 2016-07-21 at 20 58 37](https://cloud.githubusercontent.com/assets/893837/17035117/fce0bdac-4f85-11e6-9fd2-7c38b87f16ee.png)

1. It means that you didn't build the app on your iOS device, select your iOS device in the list here where to build.
2. And then press CMD+R or click the "play" icon to build the app and run it on your connected iOS device. 
3. After it started you can have access to simulate locations.

---

Be sure to read known issues on the README and serch through the issues.
