### ISSUE TITLE
No provisioning profiles were found

### ISSUE THREAD

**Issue by bello356** [iam4x/pokemongo-webspoof#69]
![screen shot 2016-07-20 at 2 07 34 am](https://cloud.githubusercontent.com/assets/20551771/16976777/634f769a-4e1f-11e6-8560-bedaeb506784.png)

When I click on fix issue it tells me 

![screen shot 2016-07-20 at 2 13 15 am](https://cloud.githubusercontent.com/assets/20551771/16976799/86086eda-4e1f-11e6-8985-9228eca96adb.png)

I tried doing it online, but it seems like I have to pay a lot of money to do so? Or am I just doing it wrong completely?

**Comment by bello356** [comment]
Help :3

**Comment by AbelIngrand** [comment]
Did you add your Apple ID to Xcode ?

**Comment by bello356** [comment]
I did, I just don't know how to add a device in members center

**Comment by muescha** [comment]
Did you add a device?

http://www.aquafadas.com/de/documentation/article/adding-devices-to-your-apple-developer-account/

**Comment by iam4x** [comment]
Just login to your apple id on Xcode and then it should fixes all theses issues by itself. You should see a button: `Fix issues` that does the work for you:

![screen shot 2016-07-21 at 21 13 58](https://cloud.githubusercontent.com/assets/893837/17035533/108d4026-4f88-11e6-8f76-35fe48bc0822.png)
