### ISSUE TITLE
Only 10 App ID's every 7 days

### ISSUE THREAD

**Issue by Pokegopla** [iam4x/pokemongo-webspoof#70]
It gives me this message when I try to build it to my iPhone. Is there something i can do about it or not?

Do I have to create new apple ID's?

**Comment by AbelIngrand** [comment]
You should choose an App ID and use it once and for all. You do not need a new App ID every time you launch the app.

Try setting it to an App ID you used before and it should work fine.

**Comment by muescha** [comment]
this should be noted in readme to use a identifier after update

**Comment by AbelIngrand** [comment]
Yes it should be updated every time the app is updated

**Comment by iam4x** [comment]
Thank's @AbelIngrand I was not aware to this new free apple developer 👍
