### ISSUE TITLE
ZERO_RESULTS

### ISSUE THREAD

**Issue by jctissier** [iam4x/pokemongo-webspoof#72]
As soon as i run the simulate location > pokemon location, i end up in the middle of the ocean and if i try to enter a destination, it gives "error with schedule trip, ZERO_RESULTS". There's no way to fix it, any idea what to do?

**Comment by muescha** [comment]
did you use the right location setting from [#5:comment](https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233739078)

**Comment by iam4x** [comment]
It's a bug that you can track into: #62
