### ISSUE TITLE
No autopilot

### ISSUE THREAD

**Issue by Lezul** [iam4x/pokemongo-webspoof#73]
For some reason, when I enter and click on an address, I do not get any of the walk/subway options. It just instantly teleports me to the location.

EDIT: Spelling/Grammar errors :/

**Comment by muescha** [comment]
this direct teleports should be somehow disabled (to avoid a soft ban - see #87 )

**Comment by iam4x** [comment]
@Lezul It seems like you are running an old version, please download: https://github.com/iam4x/pokemongo-webspoof/releases/tag/v1.1.0
