### ISSUE TITLE
Would be great to be able to customize the xcproject settings permanently

### ISSUE THREAD

**Issue by gyfis** [iam4x/pokemongo-webspoof#75]
For instance, I'd like to change the bundle identifier so it remembers and loads with the same string - easier than to type each time. The same goes for team but I suppose that one could be harder.

Thanks for the repo!

**Comment by iam4x** [comment]
Was thinking about this as well, I have an idea. But need to fix bugs first.

**Comment by NicholasHord** [comment]
Like this idea, thank you @iam4x ! Love this app

**Comment by NicholasHord** [comment]
Great idea, thank you @iam4x

**Comment by joshpalan** [comment]
@iam4x I have found that if you show package contents on the .app and navigate down to pokemongo-webspoof.app/Contents/Resources/app/xcode-project, open the xcode project from here, edit the files, then save them, the next time the app is ran it will open with your new settings.

**Comment by gyfis** [comment]
@joshpalan Great! That's definitely a viable workaround for me, thanks for pointing this out!

**Comment by gyfis** [comment]
Since the development halted and there's a workaround available too, I'm closing this.
