### ISSUE TITLE
Xcode stops running the app

### ISSUE THREAD

**Issue by Japocino** [iam4x/pokemongo-webspoof#76]
After using the app a couple of minutes Xcode stops running the app out of the sudden.
Message in Xcode bar is just: "Finished running pokemon-webspoof on ..."

**Comment by mrsimo** [comment]
This is happening to me too. I'm not all too familiar with XCode or IOS development to figure out why, but it stops working at some point and the location is reset to my current (real) one.

**Comment by AbelIngrand** [comment]
This happens sometimes when the app is inactive for too long and the system needs memory, it kills the app.

What you can do is switch to the blank app from time to time or try to quit every other apps.

There's no real fix for that that I'm aware of.

**Comment by danielsantiago** [comment]
I post the solution here: https://github.com/iam4x/pokemongo-webspoof/issues/12#issuecomment-233949763

I'm waiting for someone with more experience with xcode to make a pull request

**Comment by Flemoz** [comment]
I noticed it happens sometimes as well when visiting gyms. Sometimes it works, sometimes it quits the app. Dunno if visiting gyms requires more memory and therefore kills it?

**Comment by tiagocardosoweb** [comment]
Yeh I'm aware of this situation, and the problem continues, after 1h or something App stop running.
