### ISSUE TITLE
Error autoclick Xcode - Code 2

### ISSUE THREAD

**Issue by yhtomitk** [iam4x/pokemongo-webspoof#79]
execution error: System Events got an errer: Can't get menu bar 1 of process "Xcode". Invalid index. (-1719)

**Comment by AbelIngrand** [comment]
This issue as already been addressed here https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233124626

**Comment by iam4x** [comment]
Duplicate of #5 and please look to https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874
