### ISSUE TITLE
pokemon texture missing while using the app

### ISSUE THREAD

**Issue by rosierapathy** [iam4x/pokemongo-webspoof#80]
i can run the app smoothly but it made all the pokemon textures missing from the game (cant see the pokemon): on capture pokemon screen, on pokedex, on pokemon details, etc

**Comment by AbelIngrand** [comment]
This looks more like a bug in the Pokemon Go client. This project doesn't tamper the client data, it just uses Xcode GPS location simulation feature to change the phone's GPS coordinates.

Have you tried force quitting Pokemon Go ? Does this only happens when you use webspoof?

**Comment by rosierapathy** [comment]
yep this happens while using the webspoof, i tried quitting/reinstalling still no pokemon texture,

but i've tried again and no missing texture now, dunno what happened i guess something wrong on my side
