### ISSUE TITLE
Cannot catch pokemons

### ISSUE THREAD

**Issue by xDae** [iam4x/pokemongo-webspoof#86]
Hi, I can launch successfully the app, but there are some problems when I go to place via app:

- When I see a Pokemon and I want to catch them its impossible, all of them got out of the pokeball and run away

- Also, i cannot take objects form any pokestops (sometimes, it says im far away)

**Comment by AbelIngrand** [comment]
It seems that you have been soft banned from the game. Wait couple hours and it should work fine.

To avoid being banned again, don't change your location to fast: the ban is issued if the server sees you traveling a too long distance in a short amount of time.

**Comment by AbelIngrand** [comment]
@iam4x You could probably add this to the Readme ?

**Comment by dubert** [comment]
This happened to me too. Soft banned. This is important to note. Don't teleport places.

**Comment by iam4x** [comment]
Fixed by https://github.com/iam4x/pokemongo-webspoof/commit/3217c10b207129dc3063436d3c329208f9cafda2
