### ISSUE TITLE
Add a warning for long distances teleport to avoid soft bans

### ISSUE THREAD

**Issue by AbelIngrand** [iam4x/pokemongo-webspoof#87]
It could be nice to add a warning when using Teleport or moving the location too fast to prevent users from getting soft banned

i.e.: https://github.com/iam4x/pokemongo-webspoof/issues/86 or https://github.com/iam4x/pokemongo-webspoof/issues/81

**Comment by AbelIngrand** [comment]
Perhaps also add a warning directly in the app as most people don't read the Readme ?

**Comment by dubert** [comment]
I would put it on the blank page. As well as some of the other common issues.

**Comment by iam4x** [comment]
Fixed on README
