### ISSUE TITLE
Xcode-8 support

### ISSUE THREAD

**Issue by anushkmittal** [iam4x/pokemongo-webspoof#9]
How can I make it run on my iOS 10 device?

**Comment by iam4x** [comment]
@anushkmittal It should be working with latest release, what issue are you running into?

(ps: I'm using Xcode-beta 8 also)

**Comment by anushkmittal** [comment]
I am getting an auto-click error of can't get menu item. Besides, the Xcode app launches by default instead of Xcode-beta. I've already changed the applescript from Xcode -> Xcode-beta

**Comment by iam4x** [comment]
apple script should remain Xcode no matter what version 👍

**Comment by anushkmittal** [comment]
Ok.. I changed the Apple Script back and although I don't get any errors now but still the auto-click doesn't work

**Comment by iam4x** [comment]
Without errors it's hard to tell, can you try to clone the repo and:

(You will need nodejs v6)

`* $ npm install`
`* $ npm run dev`

Then when app is started CMD+ALT+I to open chrome dev tools and see in the console what happens wrong.

**Comment by anushkmittal** [comment]
Now, I’m getting this error being displayed in the app even after repeatedly trying to toggle simulation state

Can’t get menu item "pokemonLocation" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode". (-1728)

**Comment by iam4x** [comment]
Go back to Xcode, click into top menu bar Debug -> Simulate Location -> pokemonLocation

Try this several times it should work

**Comment by iam4x** [comment]
Is it working correctly for you now @anushkmittal ?
