### ISSUE TITLE
warning: skipping file '/pokemongo-webspoof-master/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

### ISSUE THREAD

**Issue by Hack4Life** [iam4x/pokemongo-webspoof#93]
I get the following warning when I build and run the project on my iPhone:
`warning: skipping file '/pokemongo-webspoof-master/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)`

xCode shows the file `pokemonLocation.gpx ` in red and I cannot open it. If i want to open it in finder, it opens the pokemongo-webspoof folder where no file is named pokemonLocation.gpx.

Hope you can help.

**Comment by munq** [comment]
#38 addresses this I think

**Comment by AbelIngrand** [comment]
As mentioned in #38, it's just a warning the first time you launch the app, don't worry about it.
