### ISSUE TITLE
IOS 10?

### ISSUE THREAD

**Issue by Vvkmnn** [iam4x/pokemongo-webspoof#97]
Hey, amazing piece of work. I just keep getting the following error:

`iOS Deployment Target '9.3' is newer than SDK 'IOS 9.2' in target pokemon-webspoof`

I'm new to Xcode, is there any way I can possibly fix this on my end?

**Comment by AbelIngrand** [comment]
In the project settings (click on the .xcodeproject in the left bar) set the deployment target to 9.2

**Comment by Vvkmnn** [comment]
Thanks!

Now I appear to be getting:

`A build only device cannot be used to run this target.`

Do I need an Apple Developer account?

**Comment by AbelIngrand** [comment]
Do you have the latest version of Xcode ? You need to fill in you Apple account in Xcode preferences (it's not mandatory to have a developer account)

**Comment by Vvkmnn** [comment]
Nope, I'll download the [Xcode 8 beta](https://developer.apple.com/download/ ) right now.

**Comment by AbelIngrand** [comment]
No I meant latest non beta Xcode version, you don't need the beta.

**Comment by Vvkmnn** [comment]
Oh whoops. Alright, updating from 7.2.1 to 7.3.1

**Comment by filpet** [comment]
I also get the error: "**Could not find Developer Disk Image**"

When building, I receive the following issues:

"The provisioning profile "iOS Team Provisioning Profile: ********" is expiring soon" - I think this one is to be ignored

"warning: skipping file '/var/folders/ln/cqb28qw95v70kcr9bz9x2st80000gn/T/tmp-18261DnBqPLkH4nhI/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)" - maybe this is the problem?

I use Xcode 7.3.1 with macOS and iOS 10

Thanks for your help!

**Comment by AbelIngrand** [comment]
If your iPhone is on iOS 10 you must use Xcode 8 beta. The gpx warning is meaningless, ignore it.

**Comment by Vvkmnn** [comment]
Hey, I appear to finally have something working with Xcode 8 Beta and all the steps covered up there. My character is at point 0,0 in the game. 

Last error: 
`Error with schedule trip: ZERO_RESULTS`

**Comment by Vvkmnn** [comment]
Nvm, suddenly started working for me somehow. Not sure why. Maybe the accessibility thing?

**Comment by Vvkmnn** [comment]
Also, this is probably a dumb question, but is there a way to save my xproject settings? I have to run through these steps every time I launch the app. Also, is there a way to set Xcode to run until manually cancelled? It seems to shut down randomly in the background.

**Comment by AbelIngrand** [comment]
No way for now to save the xproject settings but someone already mentioned it in another issuer.

Is Xcode shutting down or the iOS app ?

**Comment by Vvkmnn** [comment]
Fair enough.

I believe Xcode is shutting down; I have to re-run it after it stops randomly. The app on the phone appears to be there.

**Comment by AbelIngrand** [comment]
That's probably due to Xcode 8 being unstable due to its beta status.

**Comment by lukeberry99** [comment]
@Vvkmnn @AbelIngrand @iam4x the app stops running on the phone due to a memory issue, the exact error from the debugger is `Message from debugger: Terminated due to memory issue` - that's all that is logged. I'm yet to do any profiling to figure out what the exact memory issues are.

Running on iOS10 and Xcode 8.

**Comment by AbelIngrand** [comment]
Do you run the latest version with the audio background ?

**Comment by lukeberry99** [comment]
Latest version of what?

**Comment by iam4x** [comment]
Release wasn't bundled yet, I'll close this it will be in next release.

Thank's @AbelIngrand for the support 👍
