### ISSUE TITLE
Does not work error

### ISSUE THREAD

**Issue by jst94** [iam4x/pokemongo-webspoof#98]
Hey all,

I get 2 problems when running this app
1: Warning: skipping file '/Users/Jeroen/Downloads/pokemongo-webspoof-master/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

it wont show the pokemonlocation under debug.

2: it never opens a map or something and also i cant find this option: 
5. Check the `Auto update Xcode location` in the app when everything is running

It installs the app on my phone normal and it runs it but nothing happens.

Xcode 8 with ios 10

**Comment by AbelIngrand** [comment]
Please read other issues before posting. Your problem is already addressed in #74 for the blank screen, #38 for the gpx warning.

As for no map showing, relaunch the app, it can be slow to load on old computers. The auto update button will be in the webspoof app, not the iPhone app.

**Comment by iam4x** [comment]
Thank's @AbelIngrand for support.

@jst94 read https://github.com/iam4x/pokemongo-webspoof/issues/28#issuecomment-233265874 also
