### ISSUE TITLE
[Feature Request] 'Walk Around'

### ISSUE THREAD

**Issue by bgirer** [iam4x/pokemongo-webspoof#99]
Awesome job with Autopilot! Works great. Was hoping for an additional, similar feature to 'walk around' a user-created geofence. Would be useful for high-activity areas.

**Comment by d3viant0ne** [comment]
@bgirer - We are discussing "pin drop" in another thread. Autopilot + pin drop into an array of waypoints would essentially create routes which is in essence what you are looking for no?

**Comment by iam4x** [comment]
dup of #42
